In [200]:
# Installing the required libraries
!pip install pyodbc
!pip install unidecode

Requirement already satisfied: pyodbc in /opt/anaconda3/lib/python3.12/site-packages (5.0.1)
Requirement already satisfied: unidecode in /opt/anaconda3/lib/python3.12/site-packages (1.2.0)

In [201]:
# Importing the required libraries
import numpy as np
import pandas as pd
from unidecode import unidecode
import re
import datetime

In [202]:
# # Establish connection to my sql server

# server = 'FAHEEM473F\SQLEXPRESS'
# database = 'analytics_projects'

# connection_string = (
#     "DRIVER = {ODBC Driver 17 for SQL Server};"
#     f"SERVER={server}"
#     f"DATABASE={database};"
#     "Trusted_Connection=yes;")
# conn = pyodbc.connect(connection_string)

In [203]:
customers= pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_customers_dataset.csv")

## Olist_Customers_Dataset

In [205]:
customers.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
77390,b9da524b08224eaff1bf76ef4d4299ac,bef3ce10ea5715fbcbcbe3b266ee94c5,18800,piraju,SP
63096,22f9ada7e24f7c3120649acbf2dfa44a,cc5114f4de3aff0cb9652d63aa842185,72220,brasilia,DF
66589,dbce625996b257695026f8bd3c5ee160,80ac9b7155f022c3478998f6f0cd8043,4763,sao paulo,SP
71874,35ba8f2876a0059b2946b6674856c6dd,ee877710f00b0566acd13ec1a6aac8ee,83065,sao jose dos pinhais,PR
24647,15f254150d0e0f1fc6358514691f65bc,4769375f521ea3f106d30d3f92f3ad3d,20940,rio de janeiro,RJ
43575,9f8e8c99b0d702b71d105b8d922bc579,7f3ab402eb905de465544315c2469dcf,2222,sao paulo,SP
88351,22e40f23e407606505fea9fbe15b9ad4,aaf915da4aea5e5bcd55fc6daf8abe92,89652,ibiam,SC
70270,223811908c4b45b0238ea546789c3c4b,fa3fda87f7149d65fb083ae77a611085,8780,mogi das cruzes,SP
92200,b062e21ddddbe16aeb797c181e1781e1,ab2833d17fa6bccadb045eaf458e7e5e,11704,praia grande,SP
28162,adb85ff55e0f765c156f8738957050d1,6c3149b464ba67c6ce241be6d89c9a75,11320,sao vicente,SP

In [206]:
customers["customer_city"] = customers["customer_city"].str.title()

In [207]:
customers.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
82019,23e138f6446b78ec7e1ce525a6b58680,fe748aca39dd588cad3184f297c78e13,22793,Rio De Janeiro,RJ
19995,d3fcc52e324c3c31feadab1600cee977,66655cc85ad2fc7afa12e09ac2154a29,35160,Ipatinga,MG
98718,5aa439f5f53153b4ba0aca0c5a39fcf6,3872dc3409c953b02afd0feda0b1d812,66053,Belem,PA
62254,a2cc9f80829ee0d67d9767a999c9de40,43b74cf6f2f3c0de4af0bfce0e57a9eb,12223,Sao Jose Dos Campos,SP
12089,7df71d1652cfba8b2a70cf665c960f74,cb644c8c88c4705149fc0c7dd12d596d,85950,Palotina,PR
98553,4f59a5ae9f9bd9028e34ff7059119ddf,07a74ede472d8ec78c26b7a0e21848ee,8576,Itaquaquecetuba,SP
11239,53c00128b4cdd554611efd233859dd88,a91ca5a84835eabaf3fc6846aa792e1b,22630,Rio De Janeiro,RJ
25568,4d719448b1cc626699bc3bbbdbbc0bb7,4d105247e7260e45d3eab6ab9245ff03,35700,Sete Lagoas,MG
70357,1deba485fcad64cbefddbe4e64b55bc2,a06a4e8e7028865de4b4570517141704,45690,Una,BA
80674,8bc87de58bff48516a1abd472e01183e,34e8f217a80ccf05d7f69a2c5a1f9039,49100,Sao Cristovao,SE

In [208]:
customers['customer_id'].nunique()

99441

In [209]:
customers['customer_unique_id'].nunique()

96096

In [210]:
customers['customer_unique_id'].duplicated().unique()

array([False,  True])

"""customer_unique_id has some duplicated values, therefore, not a suitable candidate for a primary key.
    Also depending on, which one of the both columns was used in other tables, we will decide whether to keep or drop it."""

In [212]:
customers.drop(columns=['customer_unique_id'], inplace=True)

In [213]:
customers

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,Campinas,SP
...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,3937,Sao Paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,6764,Taboao Da Serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,60115,Fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,92120,Canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,6703,Cotia,SP

## Olist_Geolocation_Dataset

In [215]:
import pandas as pd

In [216]:
geo = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_geolocation_dataset.csv")

In [217]:
geo.sample(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
260411,11740,-24.085035,-46.801092,itanhaém,SP
271785,12228,-23.271361,-45.886719,sao jose dos campos,SP
517912,28605,-22.273175,-42.532429,nova friburgo,RJ
769659,68371,-3.202084,-52.211002,altamira,PA
349220,15055,-20.797482,-49.364052,sao jose do rio preto,SP
695176,45960,-17.382288,-40.239233,medeiros neto,BA
990893,98280,-28.315902,-53.509107,panambi,RS
822591,78143,-15.672374,-56.134009,varzea grande,MT
192390,7776,-23.333253,-46.839982,cajamar,SP
996839,99260,-28.569989,-51.976094,casca,RS

In [218]:
geo['geolocation_city'] = geo['geolocation_city'].str.title()

In [219]:
geo.sample(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
642408,38195,-19.938510,-47.547041,Conquista,MG
831662,78850,-15.557564,-54.304074,Primavera Do Leste,MT
804104,75260,-16.691520,-49.080655,Senador Canedo,GO
617292,36570,-20.757528,-42.877786,Vicosa,MG
39748,2914,-23.503784,-46.709764,São Paulo,SP
965409,95190,-28.964148,-51.071613,São Marcos,RS
322280,13807,-22.400802,-46.968171,Mogi Mirim,SP
596626,35560,-20.068266,-45.335753,Santo Antonio Do Monte,MG
726614,57035,-9.656046,-35.706489,Maceió,AL
528006,29075,-20.265955,-40.298302,Vitoria,ES

In [220]:
geo.duplicated().sum()

np.int64(261831)

In [221]:
geo.drop_duplicates(inplace=True)

In [222]:
geo.shape

(738332, 5)

""" In powerBI, we can use city column for location, so there is no need to keep the latitude and longitude columns. 
    But the city names need to be converted into english, as powerBI supports only english for city names"""

In [224]:
geo.drop(columns=['geolocation_lat', 'geolocation_lng'], inplace=True)

In [225]:
geo.sample(10)

        geolocation_zip_code_prefix geolocation_city geolocation_state
434027                        21721   Rio De Janeiro                RJ
733593                        58704            Patos                PB
194575                         8021        Sao Paulo                SP
278100                        12412  Pindamonhangaba                SP
439184                        22071   Rio De Janeiro                RJ
956242                        93285           Esteio                RS
127609                         5428        Sao Paulo                SP
540918                        29909         Linhares                ES
312745                        13568       Sao Carlos                SP
679704                        41830         Salvador                BA

In [226]:
geo['geolocation_city'].sample(10)

981076            Dom Pedrito
636399               Andradas
297719               Valinhos
342642             Araraquara
391722              Cerquilho
614285    Santa Cruz De Minas
190676              Mairipora
382530               Sorocaba
16213               Sao Paulo
493457            Nova Iguacu
Name: geolocation_city, dtype: object

""" unidecode is used to remove any impurity from english language only """

In [228]:
geo['geolocation_city'] = geo['geolocation_city'].apply(lambda x: unidecode(x))

In [229]:
geo.geolocation_city.sample(10)

353031                  Olimpia
632111    Santa Rita Do Sapucai
450023           Rio De Janeiro
29536                 Sao Paulo
910217       Balneario Camboriu
480547                   Tangua
303049                    Salto
680266                 Salvador
180522                Guarulhos
243730                  Diadema
Name: geolocation_city, dtype: object

In [230]:
geo.geolocation_city.nunique()

5969

In [231]:
geo['geolocation_zip_code_prefix'].value_counts()

geolocation_zip_code_prefix
38400    779
35500    751
11680    727
11740    678
36400    627
        ...
90038      1
90002      1
29174      1
72230      1
45824      1
Name: count, Length: 19015, dtype: int64

In [232]:
geo['geolocation_city'].value_counts()

geolocation_city
Sao Paulo                  99645
Rio De Janeiro             35177
Belo Horizonte             19474
Curitiba                   11263
Brasilia                    8791
                           ...
Cachoeira De Santa Cruz        1
Quixaba                        1
Curumim                        1
Xangrila                       1
Bento Fernandes                1
Name: count, Length: 5969, dtype: int64

In [233]:
def contains_number(s):
    return any([char.isdigit() for char in str(s)])

In [234]:
geo[geo['geolocation_city'].apply(lambda x: contains_number(x))]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
377210,17970,Sao Joao Do Pau D%26Apos%3Balho,SP
538905,29735,Quilometro 14 Do Mutum,ES
539470,29735,Quilometro 14 Do Mutum,ES
726758,57010,Maceia3,AL
786179,71880,Riacho Fundo 2,DF
823386,78278,Lambari D%26Apos%3Boeste,MT
896733,87365,4O. Centenario,PR
896977,87365,4o Centenario,PR
897217,87365,4o Centenario,PR
977775,96130,Colonia Z-3,RS
977787,96130,Colonia Z-3,RS
977813,96130,Colonia Z-3,RS

In [235]:
def keep_only_text(s):
    return ' '.join(re.sub(r'[^A-Za-z \s]', ' ', s).split())

In [236]:
geo['geolocation_city'] = geo['geolocation_city'].apply(lambda x: keep_only_text(x))

In [237]:
geo[geo['geolocation_city'].apply(lambda x: contains_number(x))]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [238]:
geo.duplicated().sum()

np.int64(718776)

In [239]:
geo[geo['geolocation_zip_code_prefix'] == 17970]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
376805,17970,Sao Joao Do Pau D Alho,SP
376827,17970,Sao Joao Do Pau D Alho,SP
376905,17970,Sao Joao Do Pau D Alho,SP
376937,17970,Sao Joao Do Pau D Alho,SP
377022,17970,Sao Joao Do Pau D Alho,SP
377073,17970,Sao Joao Do Pau D Alho,SP
377082,17970,Sao Joao Do Pau D Alho,SP
377092,17970,Sao Joao Do Pau Dalho,SP
377138,17970,Sao Joao Do Pau D Alho,SP
377186,17970,Sao Joao Do Pau Dalho,SP
377210,17970,Sao Joao Do Pau D Apos Balho,SP
377306,17970,Sao Joao Do Pau D Alho,SP
377324,17970,Sao Joao Do Pau D Alho,SP
377331,17970,Sao Joao Do Pau D Alho,SP
377496,17970,Sao Joao Do Pau D Alho,SP

In [240]:
geo.duplicated().sum()

np.int64(718776)

In [241]:
geo.drop_duplicates(inplace=True)

In [242]:
geo.shape

(19556, 3)

In [243]:
pd.set_option('display.max_rows', 100)

In [244]:
geo.reset_index(drop=True, inplace=True)

In [245]:
geo.reset_index(drop=True, inplace=True)
geo = geo[~geo['geolocation_zip_code_prefix'].duplicated()]

""" We could also apply the same steps with the city column in the customer's table, so let's do that """

In [247]:
customers['customer_city'] = customers['customer_city'].apply(lambda x: keep_only_text(x))

In [248]:
customers['customer_city'] = customers['customer_city'].apply(lambda x: unidecode(x))

In [249]:
customers.duplicated().sum()

np.int64(0)

In [250]:
customers.sample(10)

,customer_id,customer_zip_code_prefix,customer_city,customer_state
25715,e899215e0960eab10aba098c747f2c88,13904,Amparo,SP
53956,99a24036cf2d3673ae33a0c9399d4834,66823,Belem,PA
72330,ecdc08c51f6d63e91243f052db3a5bae,55004,Caruaru,PE
7899,39b59b462888c0b541d1550612718ea0,95920,Boqueirao Do Leao,RS
22151,75ae88f78b6ff4cde016ee3108c47eb6,30532,Belo Horizonte,MG
61678,6c4db8956588a32f2e15cd587c31c12f,4332,Sao Paulo,SP
9244,bcd6177c66b0830d80c820029b484afa,89201,Joinville,SC
13199,c591b62b0d38be0089c516584f6671db,21041,Rio De Janeiro,RJ
5867,4bbb5426eea4b9ecab0158949f4e0e9e,89124,Benedito Novo,SC
66422,83f9a2d3f4a98dcdbfb23e433998ec34,23036,Rio De Janeiro,RJ

In [251]:
geo.reset_index(drop=True, inplace=True)

customers.reset_index(drop=True, inplace=True)

## Olist_Products_dataset

In [253]:
products = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_products_dataset.csv")

In [254]:
products.sample(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
22808,2c14830d33060649974768f49b7abd89,bebes,50.0,1075.0,3.0,1100.0,42.0,25.0,15.0
30486,1f13ebbc80d3713a1abdd12696605956,consoles_games,57.0,799.0,1.0,775.0,29.0,21.0,25.0
23365,25179680ecacb54a036e9cdd27459da3,instrumentos_musicais,42.0,442.0,4.0,8450.0,78.0,19.0,49.0
7870,9234cd3c6bd121932ef77a39d6d87893,cool_stuff,60.0,1702.0,4.0,200.0,17.0,7.0,17.0
31376,bead7727f31b655a7f9a92a6a58e1b4d,cama_mesa_banho,52.0,275.0,1.0,600.0,34.0,23.0,43.0
21355,1596772dbdf700f2e7dd35248fcde3aa,esporte_lazer,52.0,3541.0,1.0,2100.0,20.0,20.0,20.0
29085,107fde0930956120d1e13dd1062fbb46,moveis_colchao_e_estofado,51.0,418.0,1.0,30000.0,60.0,73.0,60.0
16727,de89f330c497e12d2510c2cd2a48a29f,telefonia,30.0,900.0,1.0,605.0,16.0,14.0,16.0
18512,20e5127b0dda6370dd7795b2952da13a,moveis_decoracao,58.0,2043.0,4.0,1450.0,69.0,11.0,11.0
32084,d472a70d40f4f72dfd5f6024cfc89a13,casa_construcao,56.0,780.0,1.0,1167.0,22.0,22.0,22.0

In [255]:
products.drop(columns=['product_name_lenght', 'product_description_lenght', 'product_weight_g', 
                       'product_length_cm', 'product_height_cm', 'product_width_cm'], inplace=True)

In [256]:
products.sample(10)

,product_id,product_category_name,product_photos_qty
21088,4c048153f092e7d523dae06bc7f6becd,relogios_presentes,3.0
22729,b13b41e7467cf4ec18fceb0c4b0e6220,utilidades_domesticas,1.0
24605,7f70545e9d4c47a4e84278437672f03f,eletrodomesticos,1.0
31583,da9d5b38b3e2e1c8cb2731aa7e8bec8c,beleza_saude,1.0
15200,33f789f4b4fa74053af0199658b78853,informatica_acessorios,1.0
23351,79b45f6fe16c752af64c050de4566693,beleza_saude,1.0
31257,21b4d9c7183dd6f20f584f35c09bd361,alimentos,1.0
20207,aa24c81b22e63fb31eeefc10f52d4350,bebidas,2.0
27053,b7adcb01af7ce9db1f8192b9de8a923f,cama_mesa_banho,3.0
20541,f638a5563e72783a14acd5da63e6e372,eletrodomesticos,3.0

In [257]:
products.dropna(inplace=True)

In [258]:
products['product_category_name'].isnull().sum()

np.int64(0)

In [259]:
products['product_category_name'].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio',
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [260]:
products.reset_index(drop=True, inplace=True)

## Olist_product_name_translation_dataset

In [262]:
translation = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/product_category_name_translation.csv")

In [263]:
translation.sample(10)

                 product_category_name    product_category_name_english
2                           automotivo                             auto
36  construcao_ferramentas_ferramentas          costruction_tools_tools
54                    artigos_de_natal               christmas_supplies
28             fashion_roupa_masculina            fashion_male_clothing
29                            pet_shop                         pet_shop
70                  seguros_e_servicos            security_and_services
65                        dvds_blu_ray                     dvds_blu_ray
17         fashion_bolsas_e_acessorios         fashion_bags_accessories
25   construcao_ferramentas_construcao  construction_tools_construction
62                     casa_conforto_2                   home_comfort_2

In [264]:
products.sample(10)

,product_id,product_category_name,product_photos_qty
7524,bd5b04e67f3659248acfb0c61c08a9c1,cama_mesa_banho,1.0
23709,f999580a69ce2d199677c5b6a5472aee,automotivo,1.0
12286,6ef77c360c5206f18e444f0d170a3a01,beleza_saude,2.0
26743,154cacf31b15a08f71d7666a1ac3c0bf,informatica_acessorios,1.0
2830,a270b2f4aad055863b643395b987d151,esporte_lazer,2.0
13843,54a5943820887ae6827319853d00887d,telefonia,3.0
11545,70eb8ec63fd4f2a0bf8607712407727c,moveis_decoracao,1.0
17457,4fbd8f51817097372c985d1d042cdeed,esporte_lazer,5.0
16544,f78279f3d11f68fffc3121f3295a5871,esporte_lazer,1.0
30678,865444ecac22985b455244843197e147,instrumentos_musicais,3.0

In [265]:
print(products['product_category_name'].nunique())
print(translation['product_category_name'].nunique())

73
71

In [266]:
products[~products['product_category_name'].isin(translation['product_category_name'])]

,product_id,product_category_name,product_photos_qty
1581,0105b5323d24fc655f73052694dbbb3a,pc_gamer,4.0
5703,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1.0
7176,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1.0
7326,6727051471a0fc4a0e7737b57bff2549,pc_gamer,3.0
8648,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,2.0
10823,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1.0
13996,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,1.0
15875,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,4.0
16609,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,6.0
17460,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,5.0
18252,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,1.0
26398,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,4.0
29370,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,1.0

In [267]:
products['product_category_name'] = products['product_category_name'].apply(lambda x: 'pcs' if x == 'pc_gamer' else \
                                           'portateis_casa_forno_e_cafe' if x == 'portateis_cozinha_e_preparadores_de_alimentos' else x)

In [268]:
translation.reset_index(drop=True, inplace=True)

In [269]:
merged_product_translation = pd.merge(products, translation, how='inner', on='product_category_name')

In [270]:
merged_product_translation.drop(columns=['product_category_name'], inplace=True)

In [271]:
merged_product_translation

,product_id,product_photos_qty,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,1.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,1.0,art
2,96bd76ec8810374ed1b65e291975717f,1.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,1.0,baby
4,9dc1a7de274444849c219cff195d0b71,4.0,housewares
...,...,...,...
32336,a0b7d5a992ccda646f2d34e418fff5a0,2.0,furniture_decor
32337,bf4538d88321d0fd4412a93c974510e6,1.0,construction_tools_lights
32338,9a7c6041fa9592d9d9ef6cfe62a71f8c,1.0,bed_bath_table
32339,83808703fc0706a22e264b9d75f04a2e,2.0,computers_accessories
32340,106392145fca363410d287a815be6de4,1.0,bed_bath_table

In [272]:
merged_product_translation.isnull().sum()

product_id                       0
product_photos_qty               0
product_category_name_english    0
dtype: int64

## Olist_sellers_dataset

In [274]:
sellers = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_sellers_dataset.csv")

In [275]:
sellers.sample(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2678,bd1d49a326abfa9b1036772e40445430,17017,bauru,SP
1303,0bae85eb84b9fb3bd773911e89288d54,88301,itajai,SP
813,ae8bfdbf1c2a2a2dee92d799db0a31c6,85900,toledo,PR
2682,0887a9f087bcd5d9f6642b52f897fc6c,11990,cananeia,SP
893,698f5fa55a5f73d0740e9d9a773e8093,20751,rio de janeiro,RJ
3073,bbf4a892cac7b82422baa711dffb8997,82200,curitiba,PR
2859,5b33b527da3c5b969cc99dc435cad09a,87702,paranavai,PR
1665,47648caee88ccfe951fbb27fbf7b4cbe,9931,diadema,SP
2124,89f69225956f951295ca4c7fb1266553,27700,vassouras,RJ
1369,fb503a924a0b9db19d83dd0ac6dbef8c,96020,pelotas,RS

In [276]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [277]:
sellers['seller_city'] = sellers['seller_city'].str.title()

In [278]:
sellers['seller_city'].duplicated().sum()

np.int64(2484)

In [279]:
sellers['seller_city'] = sellers['seller_city'].apply(lambda x: keep_only_text(x))

In [280]:
sellers['seller_city'].duplicated().sum()

np.int64(2491)

In [281]:
sellers.sample(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2970,9cad4b68bb993ee401a3c5aaa2bc26dd,16200,Birigui,SP
425,2d42ebcda99fd55f6f4bc2f1ca035d50,76400,Uruacu,GO
314,6b1c4d4d9ccf0be3d8544eb0e71e5318,91130,Porto Alegre,RS
30,4dbd95a08b31ede5c82d3f861cb1ce1a,80210,Curitiba,PR
1947,1f7fd2a6fcd5a6fa5d8a4dabc72aaae0,95800,Venancio Aires,RS
2536,0b18d63d0cd1d723567903fd34a07df2,5141,Sp,SP
2694,cb3dd9ce66268c7a3ca7241ac70ab58c,3028,Sao Paulo,SP
2746,a1043bafd471dff536d0c462352beb48,37175,Ilicinea,MG
2122,a5259c149128e82c9d6d46e0c1c812bb,76900,Ji Parana,RO
1745,318f287a62ab7ac10b703ac37435a231,4773,Sao Paulo,SP

In [282]:
sellers.reset_index(drop=True, inplace=True)

## Olist_orders_dataset

In [284]:
pre_orders = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_orders_dataset.csv")

In [285]:
orders = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_orders_dataset.csv")

In [384]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
96274,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
96275,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
96276,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
96277,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
96278,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [286]:
d = pd.concat([orders, products], join='inner', axis=1)

In [382]:
d

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,product_id,product_category_name,product_photos_qty
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,3aa071139cb16b67ca9e5dea641aaa2f,artes,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,96bd76ec8810374ed1b65e291975717f,esporte_lazer,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,cef67bcfe19066a932b7673e239eb23d,bebes,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,4.0
...,...,...,...,...,...,...,...,...,...,...,...
32336,9d02a36395b93b35ec7f46d79ee3e8b9,9b9c07a0eaadb3eed67732a6fc954e4f,delivered,2018-01-29 18:29:35,2018-01-31 13:32:23,2018-02-01 21:46:07,2018-04-09 15:58:31,2018-03-09 00:00:00,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,2.0
32337,da07d4f43fafc6af5f26b48f87b710d8,4c64c464e6631d8e5ec399272e4e4cf8,delivered,2018-02-27 11:36:43,2018-02-27 11:50:23,2018-02-28 19:53:11,2018-03-16 10:20:37,2018-03-21 00:00:00,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1.0
32338,1b76e3d417b12339d254588a95496581,0d9ef7459dfab7b6b3f70bc5f436741d,delivered,2017-05-21 09:43:18,2017-05-21 09:55:08,2017-05-25 15:59:57,2017-05-31 14:16:43,2017-06-13 00:00:00,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1.0
32339,a889adb9dae2a1639e74395e692c0055,fbbb39b80d5d738c7060c499c8b132d0,delivered,2017-02-26 15:43:16,2017-02-26 15:55:17,2017-03-01 13:54:51,2017-03-06 08:33:47,2017-03-20 00:00:00,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,2.0
32340,e73f1e4b75fb2dfc4c18f8c2afd75687,e7067f47085adab23af0e0a72857de91,delivered,2018-05-29 08:53:36,2018-05-29 09:15:38,2018-05-30 08:53:00,2018-06-13 19:08:24,2018-07-05 00:00:00,106392145fca363410d287a815be6de4,cama_mesa_banho,1.0

In [380]:
d[d['order_id'] == '1dedb63df54bd6377bc3e2b61ec4c791']

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, product_id, product_category_name, product_photos_qty]
Index: []

In [288]:
orders.sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
55568,8c0cf4e06747b0264127ced0718f8fe2,be60de3949d43cd1799c3567eb6452b0,delivered,2018-06-04 12:22:27,2018-06-05 14:31:50,2018-06-06 07:46:00,2018-06-07 13:13:24,2018-06-28 00:00:00
23250,eb0a128259780bab9b612db54eaa8eca,8eeb3f16a6b991197431a8738689fc5b,delivered,2017-08-22 08:50:36,2017-08-23 18:30:17,2017-08-31 20:34:58,2017-09-12 16:57:26,2017-09-21 00:00:00
18382,e67ded764ce696c9991013d2bb481794,1eb4ce811b05f6d987a1435a2d4ab2c6,delivered,2017-12-02 11:51:27,2017-12-02 12:20:20,2017-12-05 17:58:51,2017-12-23 18:51:38,2017-12-27 00:00:00
30122,0849ccbfff0e8fd7168be6a62ca74a0d,0687042f138418a235175398780d7d69,delivered,2018-05-08 14:38:21,2018-05-08 14:55:46,2018-05-10 18:29:00,2018-05-16 15:22:48,2018-05-30 00:00:00
77196,01c1f3c10d2641a10cfd97ffaac0b3f5,fd8a9ce7e554b0a3b083521837d0f7c0,delivered,2017-11-28 22:08:43,2017-11-28 22:18:02,2017-12-05 23:22:02,2017-12-14 19:04:51,2017-12-29 00:00:00
63887,e412fc992ea2637ad4e76b34edd88a18,a1e66238cea795f0c30a76e9c5491bb8,delivered,2018-07-05 15:11:55,2018-07-05 16:08:18,2018-07-06 10:25:00,2018-07-13 18:19:45,2018-08-03 00:00:00
22958,058a48943f3034afea88ff56b960dfdb,ae42f7bb2b7fd41673207c4a4903b919,delivered,2017-11-02 17:25:13,2017-11-02 17:35:35,2017-11-07 15:54:58,2017-11-28 17:41:41,2017-11-29 00:00:00
43168,1c70da88ac2f845fcca28df46ba4b4fb,18c5119621cc70720226b725ffe2e03d,delivered,2017-12-23 14:48:05,2017-12-24 14:49:22,2017-12-26 21:18:42,2018-01-08 23:07:37,2018-01-19 00:00:00
6126,62b0218b2b5a838f1aa7f1fcd11a59d4,f42b6317cd949a967e625c2e66c9fba7,delivered,2018-06-23 10:23:25,2018-06-23 10:35:14,2018-06-25 14:14:00,2018-07-04 20:11:39,2018-07-24 00:00:00
57948,66f4d4cb45642e879ba8c00484e13aa8,5573b74621b2e7ef7db25cae88fa62ed,delivered,2018-05-07 16:39:05,2018-05-07 18:15:23,2018-05-08 11:19:00,2018-05-15 19:12:31,2018-05-24 00:00:00

In [289]:
orders[~(orders['customer_id'].isin(customers['customer_id']))]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [290]:
orders['order_id'].duplicated().sum()

np.int64(0)

In [291]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [292]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [293]:
orders[orders['order_approved_at'].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00
1801,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaN,NaN,NaN,2018-10-17 00:00:00
1868,df8282afe61008dc26c6c31011474d02,aa797b187b5466bc6925aaaa4bb3bed1,canceled,2017-03-04 12:14:30,NaN,NaN,NaN,2017-04-10 00:00:00
2029,8d4c637f1accf7a88a4555f02741e606,b1dd715db389a2077f43174e7a675d07,canceled,2018-08-29 16:27:49,NaN,NaN,NaN,2018-09-13 00:00:00
2161,7a9d4c7f9b068337875b95465330f2fc,7f71ae48074c0cfec9195f88fcbfac55,canceled,2017-05-01 16:12:39,NaN,NaN,NaN,2017-05-30 00:00:00
...,...,...,...,...,...,...,...,...
97696,5a00b4d35edffc56b825c3646a99ba9d,6a3bdf004ca96338fb5fad1b8d93c2e6,canceled,2017-07-02 15:38:46,NaN,NaN,NaN,2017-07-25 00:00:00
98415,227c804e2a44760671a6a5697ea549e4,62e7477e75e542243ee62a0ba73f410f,canceled,2017-09-28 15:02:56,NaN,NaN,NaN,2017-10-16 00:00:00
98909,e49e7ce1471b4693482d40c2bd3ad196,e4e7ab3f449aeb401f0216f86c2104db,canceled,2018-08-07 11:16:28,NaN,NaN,NaN,2018-08-10 00:00:00
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00

In [294]:
orders[orders['order_delivered_carrier_date'].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
266,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaN,NaN,2017-12-05 00:00:00
324,d3c8851a6651eeff2f73b0e011ac45d0,957f8e082185574de25992dc659ebbc0,processing,2016-10-05 22:44:13,2016-10-06 15:51:05,NaN,NaN,2016-12-09 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [295]:
orders[orders['order_delivered_customer_date'].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [296]:
orders['order_purchase_timestamp'] = orders['order_purchase_timestamp'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))
orders['order_approved_at'] = orders['order_approved_at'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)
orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)
orders['order_estimated_delivery_date'] = orders['order_estimated_delivery_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)

In [297]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [298]:
orders = orders[(
    ((orders['order_approved_at'] - orders['order_purchase_timestamp']).dt.total_seconds() / 86400 >= 0) &
    ((orders['order_delivered_carrier_date'] - orders['order_approved_at']).dt.total_seconds() / 86400 >= 0))]

In [299]:
orders.reset_index(drop=True, inplace=True)

In [300]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date    1174
order_estimated_delivery_date       0
dtype: int64

In [301]:
orders['order_status'].value_counts()

order_status
delivered    95112
shipped       1098
canceled        75
Name: count, dtype: int64

In [302]:
orders[(orders['order_status']=='canceled') & (orders['order_delivered_customer_date'].notna())].index

Index([2838, 8515, 56427, 57465, 89718, 91420], dtype='int64')

In [303]:
to_remove = orders[(orders['order_status']=='canceled') & (orders['order_delivered_customer_date'].notna())].index

In [304]:
orders.drop(to_remove, inplace=True)

In [305]:
orders.reset_index(drop=True, inplace=True)

In [306]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
96274,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
96275,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
96276,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
96277,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
96278,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [307]:
orders['order_status'].value_counts()

order_status
delivered    95112
shipped       1098
canceled        69
Name: count, dtype: int64

In [308]:
orders['order_status'] = orders['order_status'].str.replace('canceled', 'cancelled')

In [309]:
orders['order_status'].unique()

array(['delivered', 'shipped', 'cancelled'], dtype=object)

In [310]:
orders[orders['order_status']=='cancelled']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
597,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,cancelled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaT,2018-02-22
1035,3a129877493c8189c59c60eb71d97c29,0913cdce793684e52bbfac69d87e91fd,cancelled,2018-01-25 13:34:24,2018-01-25 13:50:20,2018-01-26 21:42:18,NaT,2018-02-23
4969,8a9cce19aa49e055f2babb81d5a71c40,f2676ef361959c938b35ecd32321adce,cancelled,2018-02-01 10:04:20,2018-02-03 02:52:42,2018-02-05 20:41:28,NaT,2018-02-23
5281,c1049eef89915c6beb3604bf3d6588d7,ed16865bcadcea1a00a928bf418a74bf,cancelled,2018-02-05 23:08:11,2018-02-05 23:29:26,2018-02-09 22:13:01,NaT,2018-03-07
5339,885935156ba43094f3ae95f3c14e0381,3885c59916b2b261205c303fe0a10abf,cancelled,2018-02-02 16:06:44,2018-02-06 04:32:39,2018-02-07 20:48:31,NaT,2018-03-08
6434,5b4858f2dcf69731f2285a38829bfa7c,c8223f76047e09bea798462f2f46ffa9,cancelled,2018-02-15 20:53:17,2018-02-15 21:06:43,2018-02-16 16:52:52,NaT,2018-03-16
7706,bef875448d5a4f703555d2dd5f8382b5,4a6f6cd7b3fa8d3f9a370adfdad0fa97,cancelled,2018-01-23 09:48:56,2018-01-23 10:20:10,2018-01-24 21:04:56,NaT,2018-02-22
14219,2cfc79d9582e9135c0a9b61fa60e6b21,f530197ea86ced9488a03d055e118ebf,cancelled,2018-02-19 17:11:34,2018-02-19 17:20:52,2018-02-20 18:58:43,NaT,2018-03-15
14303,ba0f1e99132c6f69e4622597e9853599,4624a495981365fa48c8ac2ce5fc3b3d,cancelled,2018-01-24 14:16:15,2018-01-24 15:15:57,2018-01-26 18:32:47,NaT,2018-02-21
14329,5abf37ab57e23f69a9c8ab98c4800273,19a045432879d6ddb4fd5611a0e2ba5b,cancelled,2018-01-28 00:25:15,2018-01-28 00:36:35,2018-02-01 20:07:57,NaT,2018-02-20
15044,8caf289ab5d7e3ec7b4522aa22dabbec,dca1d784fd6b8dd1f223bb76482fa053,cancelled,2018-02-14 10:37:17,2018-02-14 10:50:27,2018-02-17 00:04:14,NaT,2018-03-07
16585,943625151a5d8d00da80e96a90930e03,2953e41dea84f8fe69dc569138b6002f,cancelled,2018-02-17 09:59:29,2018-02-17 10:10:26,2018-02-20 16:48:58,NaT,2018-03-06
18390,7e30f6ae5435d7c05b487f7b5e1d61ba,c2ca5f569938a5f8a79e1f80f3800e3f,cancelled,2018-02-28 13:16:08,2018-02-28 13:35:20,2018-03-02 02:43:53,NaT,2018-03-13
18751,b7d469b7eb3c07c6d4b96d505c811fea,5b9d5dfe6b754261741fb68772efed93,cancelled,2018-02-03 22:14:25,2018-02-06 04:32:36,2018-02-06 20:46:55,NaT,2018-02-21
20455,7582b8c10039cceafcfe7b13e41a91e2,57bb0f2ff265139687180b2fb387e198,cancelled,2018-02-07 14:27:34,2018-02-07 14:35:40,2018-02-10 14:08:59,NaT,2018-03-08
20661,936a199847ccb47438d3ae454d5e18d1,8c587eca721e5478cc6bd17ac3e8cb4c,cancelled,2018-02-02 17:42:31,2018-02-02 17:52:12,2018-02-05 13:19:36,NaT,2018-03-09
21042,8f367420ab5fc7305b7383f29ef4ed4e,56be20830570df2c36d2935be6f1e417,cancelled,2018-01-30 22:32:13,2018-01-31 20:30:52,2018-02-01 22:47:53,NaT,2018-02-23
22915,f3c5d914eec90079a826c2b5ea7fe6bc,078c6672babf4cf39a551e2dcd79229e,cancelled,2018-01-26 12:58:01,2018-01-26 13:12:44,2018-01-26 21:45:07,NaT,2018-02-19
27771,2db84a082bda455eb1da10727e7ca621,12f0a2db64cb3b8ffbe0a340acb99050,cancelled,2018-02-02 15:29:05,2018-02-02 16:00:26,2018-02-06 14:54:44,NaT,2018-02-20
28796,cd94dbdc801da0cd93b0c8f33663973d,17ba50f54399b61694fbb138a3831d56,cancelled,2018-02-21 20:54:45,2018-02-21 21:29:00,2018-02-24 00:21:47,NaT,2018-03-15
29002,b8752fc264f1692031237bb715061cc4,217368c0bfd8d50699dfb3f303d4c387,cancelled,2018-02-22 16:58:06,2018-02-22 17:15:47,2018-02-23 20:49:02,NaT,2018-03-09
29299,0166cc8756d58b4a30fb49de83527120,19e9dac43eee8df98092482fdce676da,cancelled,2018-02-08 21:09:18,2018-02-08 21:27:56,2018-02-09 23:12:30,NaT,2018-02-22
30781,6b460c25c2bb8e1323536e9e921d04a1,95d2bac8c1d115b9c5291fba7b9186aa,cancelled,2018-01-29 16:07:41,2018-01-29 16:36:51,2018-01-30 21:12:59,NaT,2018-03-02
34037,3af427dfb9464cd660ac27292bb5d30b,296fcaa5fafeccd48433a91f4019d99b,cancelled,2018-01-30 13:28:14,2018-01-30 14:21:31,2018-02-01 01:58:41,NaT,2018-03-01
39150,13a60be94bc36bf7c5f1e0a849cdd6e4,fcd909bbcc659f6100bf2a987d65aca5,cancelled,2018-02-19 10:56:33,2018-02-19 11:07:50,2018-02-20 19:19:17,NaT,2018-03-15
42906,6ad336dba0613cde0e5717f50dc8c669,f6dd94c82d8cf048ef7b4df3ed7a12f7,cancelled,2018-01-25 17:18:26,2018-01-25 18:12:14,2018-01-26 20:12:58,NaT,2018-02-23
43452,8652f7789fe1585b439154b7ae0f4285,0f29ccaad86ee7442d59a69cf4166c6b,cancelled,2018-02-20 14:49:42,2018-02-20 15:09:18,2018-02-21 21:23:04,NaT,2018-03-12
46196,24f07a52ca6b749c618b46ddb2e94b8a,2fead6d196da5adf133e4ddb08f51c8c,cancelled,2018-01-30 09:39:05,2018-01-30 09:56:17,2018-01-31 23:39:52,NaT,2018-02-21
48597,a90966534748634cbb133383bf0eee68,509585871d9505d583be980046b14b8a,cancelled,2018-02-01 16:49:17,2018-02-01 17:15:39,2018-02-02 19:26:53,NaT,2018-02-19
48900,66dbde751178d7674bd09f18b6d25006,6903c9e22ca171ab56f877af3ebaa9dd,cancelled,2018-02-05 16:30:33,2018-02-05 16:52:11,2018-02-07 22:52:43,NaT,2018-03-12
49261,e248283e6b8ba09b05efea1000d9478b,7283505b00797306818c085c6baf0752,cancelled,2018-03-03 19:20:13,2018-03-03 20:00:25,2018-03-05 18:18:40,NaT,2018-03-15
51511,e7dfe42bb50a6acce37e168e44260a51,97421afb531a2c357e152626fdecd126,cancelled,2018-02-14 01:59:02,2018-02-14 02:10:22,2018-02-14 20:29:03,NaT,2018-03-09
52284,2c0032906c603dcc21cd954828fa77d0,4afea82f984caa99c5946b758f101abd,cancelled,2018-02-06 13:44:50,2018-02-06 15:55:40,2018-02-16 20:35:24,NaT,2018-03-12
52779,4be69a31714c77604076ab0004055c6c,64f5f567fef8b7faab9a3c95e572cf3c,cancelled,2018-01-31 19:30:37,2018-01-31 19:49:47,2018-02-03 02:33:05,NaT,2018-02-22
53316,cd408efeda0fdd3fe5f27134bd065001,7183e78211dd520b9a9d1ed9aa888b35,cancelled,2018-02-08 22:19:00,2018-02-08 22:30:25,2018-02-09 23:46:35,NaT,2018-02-22
55982,a2714ecbf6eeb3bb9cd7dba6dc1c5e82,5fe0562353e8f0b6c0c6b55cd0f58fe0,cancelled,2018-02-14 18:01:38,2018-02-14 18:20:40,2018-02-15 17:27:27,NaT,2018-03-06
55995,854f8cb8dacdc3abc4cce7a7df6fcc1f,58512a1043fd8047a4f96d5fa665fd2d,cancelled,2018-02-02 09:09:27,2018-02-02 09:15:27,2018-02-08 22:06:59,NaT,2018-03-06
56687,fe9fae71b4fa7d05f1934adc54391f8d,fa9db18cb6fd65d306a4d710799111a8,cancelled,2018-02-15 15:28:12,2018-02-15 15:46:54,2018-02-21 19:59:14,NaT,2018-03-07
57419,881a5cda3b897b035971e3fcfce58aa6,aabb289abf4c3277937c216d0729f36d,cancelled,2018-01-31 16:16:21,2018-01-31 16:34:19,2018-02-02 19:04:47,NaT,2018-03-01
59477,9c83e5ae8ff2b5cad999c3dc6129a888,b16ed08790d757ebcbc3533101fb1ace,cancelled,2018-03-03 09:44:30,2018-03-03 10:20:20,2018-03-05 19:19:03,NaT,2018-03-15
59800,6cf51ab464bdd9f7b282f5fe72391383,6b8d0ddc6f0be6c4895f69fae60edf2f,cancelled,2018-02-27 22:43:39,2018-02-27 22:55:52,2018-02-28 20:07:53,NaT,2018-03-13
60077,2f6492ebb2badd06db511b63ae7d7f55,0ffc8e8c374a394b0715d65963d641f1,cancelled,2018-01-20 14:59:28,2018-01-20 15:22:02,2018-01-22 17:09:37,NaT,2018-02-20
64188,e0b4e92a39bc8b93bc4ff121772819ea,df94e5683581981f437c1986e75c2a29,cancelled,2018-02-01 12:21:42,2018-02-01 12:30:36,2018-02-05 10:03:51,NaT,2018-02-19
65048,8d171a848151e69e8f090fdbb50d4010,a10afcc34f66a704819e459a8f524ffa,cancelled,2018-02-13 14:38:55,2018-02-15 04:07:13,2018-02-16 00:19:33,NaT,2018-03-09
68605,cc6c9b89f70b32d7fe075718e0fc58e7,418e9412b396846b861a8c5cb59ba65b,cancelled,2018-01-27 10:52:04,2018-01-29 10:52:24,2018-01-30 19:52:55,NaT,2018-03-02
70177,dba741d70126a95feb85435175370edc,a4426f6a2cfe4a7cea7146f236bf41ae,cancelled,2018-01-24 19:18:04,2018-01-24 19:57:20,2018-01-26 20:12:58,NaT,2018-03-05
70222,cb599c234fc71be7c137179b6d473a30,23534938f44ad51d0de4bf6a56ca1adf,cancelled,2018-01-30 20:13:33,2018-01-30 20:33:18,2018-02-01 19:38:42,NaT,2018-02-22
70908,14904245b311483b6886be3c2e717e76,a52ee9f5a35cf680f2aea9dd5fe0941e,cancelled,2018-02-12 15:49:38,2018-02-12 16:27:22,2018-02-14 19:25:00,NaT,2018-03-13
71988,c7a5d101d4b6ed70eacc97c78158eadd,9d109a169b7b88405b214e976c6039e7,cancelled,2018-02-01 19:08:48,2018-02-03 02:53:37,2018-02-06 00:49:39,NaT,2018-03-02
72036,d7cc5fcfee9af53fcd78bb47e4e55584,6c081dfe77db2d63f336f33043f0036a,cancelled,2018-01-27 10:22:47,2018-01-27 10:36:19,2018-01-30 22:24:41,NaT,2018-02-20
73114,9ec3685b1f21c7dfff4f656392b186dd,952f534f87d6ec6eeaa2cfd1d5987362,cancelled,2018-02-20 11:37:45,2018-02-20 11:50:31,2018-02-27 16:17:59,NaT,2018-03-12
73821,a8a3eaaf155bc111acb10e0536a9e753,698bbedec1b23581c4ab4aee7270057a,cancelled,2018-02-07 12:28:45,2018-02-08 17:05:57,2018-02-09 01:05:58,NaT,2018-03-09
77552,01e7cf79ff6fdb0a65634f714c67dd24,aded241eaa68c31246d82eb3198d4ae3,cancelled,2018-02-15 14:58:55,2018-02-15 15:10:35,2018-02-19 18:52:15,NaT,2018-03-07
78394,d3afe40f7060b3287d948a6bdea42687,8fcf5bb811c9f0ce5cd194b56b5f0ae4,cancelled,2018-02-05 22:13:02,2018-02-05 22:30:14,2018-02-06 21:42:51,NaT,2018-02-21
78778,ab76f54a321a0431ef243b3b6865078b,f89df6ef365783b667b626aeaffc5e2d,cancelled,2018-02-04 12:25:42,2018-02-04 12:51:26,2018-02-06 23:21:57,NaT,2018-02-21
79957,4472eca3b65b1dca5e0d59c0e4e0c6bc,5775437e881f0a230649f5c63e1f9241,cancelled,2018-02-10 07:39:19,2018-02-10 08:20:22,2018-02-15 22:22:46,NaT,2018-02-26
81070,9f0e70e8d046d9e0626bbdaf1aff88c4,6ef5c9f7a060756a678e74a07a3bdfd5,cancelled,2018-01-24 12:12:58,2018-01-24 15:16:07,2018-01-25 20:53:51,NaT,2018-03-06
81974,d0fcf3d6dcc18a5c4ac51f06a56ec683,1741b977c920605ffb564947e40cdf0b,cancelled,2018-01-31 13:05:16,2018-02-01 11:35:43,2018-02-05 16:47:42,NaT,2018-03-07
82088,6b5ccf5385890198c54fa97afe4812bc,15c523e088107f017c3b74f5874a0f43,cancelled,2018-01-30 13:37:28,2018-01-30 13:51:21,2018-01-31 17:22:03,NaT,2018-02-22
82500,46eb75885eca03736c4188871c0a9ba3,5371cc1698f54400f167d8fc79d6ad93,cancelled,2018-01-29 22:54:58,2018-01-29 23:11:24,2018-01-31 22:28:35,NaT,2018-02-23
85411,ca7296a83aa279afb28c2388a4f48891,daada56f7d2e74dfd291d652b7e03ac2,cancelled,2018-02-07 09:48:08,2018-02-07 10:10:17,2018-02-08 23:26:57,NaT,2018-03-07
87718,0e5e60b0cddf73f60eb73fac19f590cf,52222a646829d54aa33a64283f3b5549,cancelled,2018-01-28 21:31:07,2018-01-28 21:39:24,2018-01-29 19:12:01,NaT,2018-02-26
89046,41c3bd8a34828a1a9ed3bae14a535afe,4e45b6aed6be4fbe9d4a843b9055e19d,cancelled,2018-01-23 15:43:48,2018-01-24 02:35:42,2018-01-26 23:07:53,NaT,2018-02-20
90173,7a56ded9b696cca5e892f56f49b1921a,caca87282df2b6fce5e717b93e548b92,cancelled,2018-01-28 21:44:00,2018-01-28 21:58:09,2018-01-29 20:21:44,NaT,2018-03-02
90237,47e96b5cb6f0592d336b6bf8a817d1c3,9cce7727e7d1d1a738ccc755eae38e93,cancelled,2018-01-21 12:44:16,2018-01-22 13:49:10,2018-02-01 00:08:56,NaT,2018-02-19
91204,c9f06c1229ec7cd4ec9aed55d434b499,fa89053140d09081b3a3a4608a74c083,cancelled,2018-02-05 20:26:29,2018-02-05 20:49:48,2018-02-06 19:49:32,NaT,2018-03-01
93253,1def7af24cb7182497acfd953f6dd88b,b35c38c2cd6a72b58cb104154d9782e4,cancelled,2017-12-21 09:22:36,2017-12-23 02:12:37,2018-01-30 19:28:55,NaT,2018-02-20
94130,716bcd6dfe99970baf4aed2083136ed8,42715bff8f22b8dc62e5055b1e9fef7e,cancelled,2018-02-03 13:37:35,2018-02-03 13:50:26,2018-02-05 19:59:59,NaT,2018-03-01
95284,affcfd3067c168967157abe801a3c4ec,5f40f0d1ada169f5b00ec600e563826a,cancelled,2018-02-17 22:18:30,2018-02-17 22:35:29,2018-02-19 20:08:21,NaT,2018-03-06

## Olist_order_payment_dataset

In [312]:
pre_payments = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_order_payments_dataset.csv")

In [313]:
payments = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_order_payments_dataset.csv")

In [314]:
payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [315]:
payments.sort_values(by='payment_sequential', ascending=False)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
32393,ccf804e764ed5650cd8759557269dc13,26,voucher,1,23.10
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
...,...,...,...,...,...
35372,329954a78d93c0af4e24aad8677ba9bb,1,credit_card,1,83.41
35371,73130e7702a070351d67c7859ed9e12a,1,credit_card,2,60.43
35370,fcdd373db44c238886a0ecf5ec332b95,1,credit_card,4,235.48
35369,62529dde2b3d81415417822b4bc91581,1,credit_card,5,51.04
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [316]:
orders[orders['order_id'] == 'fa65dad1b0e818e3ccc5cb0e39231352']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
25113,fa65dad1b0e818e3ccc5cb0e39231352,9af2372a1e49340278e7c1ef8d749f34,shipped,2017-04-20 12:45:34,2017-04-22 09:10:13,2017-04-24 11:31:17,NaT,2017-05-18

""" we only care about order and day level granularity, so we just calculate payment_value/payment_type/order """

In [318]:
payments.drop(columns = ['payment_sequential', 'payment_installments'], inplace=True)

In [319]:
payments

                                order_id payment_type  payment_value
0       b81ef226f3fe1789b1e8b2acac839d17  credit_card          99.33
1       a9810da82917af2d9aefd1278f1dcfa0  credit_card          24.39
2       25e8ea4e93396b6fa0d3dd708e76c1bd  credit_card          65.71
3       ba78997921bbcdc1373bb41e913ab953  credit_card         107.78
4       42fdf880ba16b47b59251dd489d4441a  credit_card         128.45
...                                  ...          ...            ...
103881  0406037ad97740d563a178ecc7a2075c       boleto         363.31
103882  7b905861d7c825891d6347454ea7863f  credit_card          96.80
103883  32609bbb3dd69b3c066a6860554a77bf  credit_card          47.77
103884  b8b61059626efa996a60be9bb9320e10  credit_card         369.54
103885  28bbae6599b09d39ca406b747b6632b1       boleto         191.58

[103886 rows x 3 columns]

In [320]:
payments = payments.groupby(by=['order_id', 'payment_type']).sum('payment_value').reset_index()

In [321]:
payments.sample(10)

                                order_id payment_type  payment_value
21930   374fa6a5abe1f7de3edd2add780eb791       boleto         110.40
96217   f2314bb87d6f10a76f4a5d73c19487e3  credit_card         284.66
54851   8a8b1b373a33b3d5721b9e7c02a068f9  credit_card         159.60
26235   421deffec215845f8632fb3543789f86  credit_card         103.69
101623  ffd84ab39cd5e873d8dba24342e65c01  credit_card          65.36
17992   2d9fae00e8fabe4fc6128a1d8a527aeb  credit_card          26.39
51068   80ba49127f9a97f9bbe4e60770798cc7  credit_card          79.87
49123   7bb49ae162145b926eb697dbd5821f6a  credit_card          46.00
17342   2c0850997a2ee7ab84dbd7b4c909b667  credit_card         253.80
32965   52d460ae47aa90f9b540f2f869f62d41  credit_card         163.25

In [322]:
payments[payments['order_id']=='fa65dad1b0e818e3ccc5cb0e39231352']

                               order_id payment_type  payment_value
99453  fa65dad1b0e818e3ccc5cb0e39231352      voucher         457.99

In [323]:
orders[~orders['order_id'].isin(payments['order_id'])]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
29751,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04

In [324]:
payments[~payments['order_id'].isin(orders['order_id'])]['order_id'].nunique()

3162

In [325]:
payments.shape

(101686, 3)

In [326]:
payments['order_id'].duplicated().sum()

np.int64(2246)

In [327]:
print(orders.order_id.nunique())
print(payments.order_id.nunique())

96279
99440

In [328]:
99440 - 96279

3161

In [329]:
pre_orders[~pre_orders['order_id'].isin(orders['order_id'])]['order_id'].nunique()

3162

""" Now we need to merge both the table using inner join, since we don't need the order_ids present 
    in the payments table but not in the orders table, because of the cleaning. The order_ids present in the
    payments table are not right, so we drop them, by merging the two tables using inner join. """

In [331]:
payments.reset_index(drop=True, inplace=True)

In [332]:
pd.merge(orders, payments, how='inner', on='order_id')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.59
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.46
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.12
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.20
...,...,...,...,...,...,...,...,...,...,...
98444,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,credit_card,85.08
98445,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.00
98446,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.01
98447,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16
98448,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.86

In [333]:
merged_orders_payments = pd.merge(orders, payments, how='inner', on='order_id')

In [334]:
merged_orders_payments

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.59
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.46
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.12
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.20
...,...,...,...,...,...,...,...,...,...,...
98444,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,credit_card,85.08
98445,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.00
98446,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.01
98447,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16
98448,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.86

In [335]:
merged_orders_payments['order_id'].nunique()

96278

## Olist_order_item_dataset

In [337]:
order_items = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_order_items_dataset.csv")

In [338]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [339]:
order_items.sample(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
2254,05252513392111e8721062d8ecd9edb1,1,089cc17c8bf2226d13648392e33dabd7,70a12e78e608ac31179aea7f8422044b,2017-05-25 19:05:16,45.00,11.85
70639,a1244e1c9ad5fe2e15f97c9136ef70ab,1,a080d0af331e8a4152c49bfc8113dec9,4830e40640734fc1c52cd21127c341d4,2017-12-04 03:26:07,35.00,9.34
72596,a588eecfb1bc607f34f657272d7f8298,1,6d7a4492be45dfb8e38e762efe6614a4,ea8482cd71df3c1969d7b9473ff13abc,2017-12-06 14:17:58,27.99,25.63
92392,d199e989bbb5f7b410c1a717d589499e,1,8994980b6420059104bb47e2cb680e0a,6bb62a4912377c7bfe7cb17b406bc7e6,2018-08-02 15:44:53,16.89,11.84
104758,edfb49082a74314dd99b846ccd67b2a3,1,909b87db6cb3a7ab26bd03cc59860136,59cea8e446d3834393058e7e0666b6fb,2018-07-05 02:35:19,39.90,13.62
15397,2321337240c200736e346c2445003fd3,1,b3cd6ea8ef75cbcb2856861b31eb9bc0,966cb4760537b1404caedd472cc610a5,2018-05-16 20:17:45,519.00,11.99
46730,6a32c701681d4c31dac221f9a2848c80,1,83bfae859f4a37b048a3abcecb17c506,b6d44737c043328708f6749c2dbe50bd,2018-04-04 03:09:12,85.00,21.67
101506,e65656d2103b156e7f60dfb3e27c3762,1,8c591ab0ca519558779df02023177f44,a1043bafd471dff536d0c462352beb48,2018-03-15 14:31:24,110.00,29.08
52048,7674897136f94bdf9124c9ea0542b006,1,fb55982be901439613a95940feefd9ee,3d871de0142ce09b7081e2b9d1733cb1,2017-12-29 18:11:53,79.00,13.57
32433,4983af2477ae85a49af5ab63a208c507,1,4fa33915031a8cde03dd0d3e8fb27f01,fe2032dab1a61af8794248c8196565c9,2018-04-12 09:29:32,144.00,13.45

In [340]:
order_items[order_items['order_id'].isin(merged_orders_payments['order_id'])]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [341]:
orders_items = order_items[order_items['order_id'].isin(merged_orders_payments['order_id'])]

In [342]:
orders_items.reset_index(drop=True, inplace=True)

In [343]:
pd.merge(merged_orders_payments, order_items, how='inner', on='order_id')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.59,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.46,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.12,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [344]:
merged_orders_payments_orderItems = pd.merge(merged_orders_payments, order_items, how='inner', on='order_id')

In [345]:
merged_orders_payments_orderItems

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.59,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.46,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.12,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [346]:
merged_orders_payments_orderItems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112310 entries, 0 to 112309
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112310 non-null  object
 1   customer_id                    112310 non-null  object
 2   order_status                   112310 non-null  object
 3   order_purchase_timestamp       112310 non-null  datetime64[ns]
 4   order_approved_at              112310 non-null  datetime64[ns]
 5   order_delivered_carrier_date   112310 non-null  datetime64[ns]
 6   order_delivered_customer_date  111039 non-null  datetime64[ns]
 7   order_estimated_delivery_date  112310 non-null  datetime64[ns]
 8   payment_type                   112310 non-null  object
 9   payment_value                  112310 non-null  float64
 10  order_item_id                  112310 non-null  int64
 11  product_id                     112310 non-null  object
 12  seller_id                      112310 non-null  object
 13  shipping_limit_date            112310 non-null  object
 14  price                          112310 non-null  float64
 15  freight_value                  112310 non-null  float64
dtypes: datetime64[ns](5), float64(3), int64(1), object(7)
memory usage: 13.7+ MB

In [347]:
merged_orders_payments_orderItems['shipping_limit_date'] = \
        merged_orders_payments_orderItems['shipping_limit_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))

In [348]:
merged_orders_payments_orderItems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112310 entries, 0 to 112309
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112310 non-null  object
 1   customer_id                    112310 non-null  object
 2   order_status                   112310 non-null  object
 3   order_purchase_timestamp       112310 non-null  datetime64[ns]
 4   order_approved_at              112310 non-null  datetime64[ns]
 5   order_delivered_carrier_date   112310 non-null  datetime64[ns]
 6   order_delivered_customer_date  111039 non-null  datetime64[ns]
 7   order_estimated_delivery_date  112310 non-null  datetime64[ns]
 8   payment_type                   112310 non-null  object
 9   payment_value                  112310 non-null  float64
 10  order_item_id                  112310 non-null  int64
 11  product_id                     112310 non-null  object
 12  seller_id                      112310 non-null  object
 13  shipping_limit_date            112310 non-null  datetime64[ns]
 14  price                          112310 non-null  float64
 15  freight_value                  112310 non-null  float64
dtypes: datetime64[ns](6), float64(3), int64(1), object(6)
memory usage: 13.7+ MB

In [349]:
merged_orders_payments_orderItems[(merged_orders_payments_orderItems['shipping_limit_date'] > merged_orders_payments_orderItems['order_purchase_timestamp']) & \
(merged_orders_payments_orderItems['shipping_limit_date'] > merged_orders_payments_orderItems['order_approved_at']) & \
(merged_orders_payments_orderItems['shipping_limit_date'] < merged_orders_payments_orderItems['order_delivered_customer_date'])]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.59,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.46,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.12,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [350]:
merged_orders_payments_orderItems = merged_orders_payments_orderItems[(merged_orders_payments_orderItems['shipping_limit_date'] > merged_orders_payments_orderItems['order_purchase_timestamp']) & \
(merged_orders_payments_orderItems['shipping_limit_date'] > merged_orders_payments_orderItems['order_approved_at']) & \
(merged_orders_payments_orderItems['shipping_limit_date'] < merged_orders_payments_orderItems['order_delivered_customer_date'])]

In [351]:
merged_orders_payments_orderItems.reset_index(drop=True, inplace=True)

In [352]:
merged_orders_payments_orderItems.sort_values(by=['order_item_id' ], ascending=False)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
78604,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.80,6.57
78603,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89
83237,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.80,20,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.70,14.44
76946,1b15974a0141d54e36626dca3fdc731a,be1b70680b9f9694d8c70f41fa3dc92b,delivered,2018-02-22 15:30:41,2018-02-24 03:20:27,2018-03-02 00:18:01,2018-03-05 15:22:27,2018-03-08,boleto,2202.40,20,ee3d532c8a438679776d222e997606b3,8e6d7754bc7e0f22c96d255ebda59eba,2018-03-01 02:50:48,100.00,10.12
78602,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,19,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31212,8f22b4b97d1fd2f187f3106ffb0021c4,7543aeacbb6f5814830a5aa5c5c65090,delivered,2017-07-24 13:40:58,2017-07-25 06:43:03,2017-07-25 22:21:40,2017-08-03 19:11:21,2017-08-18,boleto,163.78,1,11875b30b49585209e608f40e8082e65,669ae81880e08f269a64487cfb287169,2017-08-01 06:43:03,65.00,16.89
31211,aceb1960c578f181bef6f5981235eb3f,8a3edfcb25845185d88c9466e067fcd2,delivered,2018-06-25 12:59:15,2018-06-25 13:48:03,2018-06-25 13:58:00,2018-06-28 18:52:03,2018-07-17,credit_card,168.80,1,b021c76fe55cfee1a103b025bda7346f,edb1ef5e36e0c8cd84eb3c9b003e486d,2018-06-27 13:17:42,149.65,19.15
31210,2cb1dbf399fd85ab146055c539b09ccf,0a1431f7019951b42e8a79ca9c9776f7,delivered,2017-10-03 15:35:27,2017-10-04 02:56:32,2017-10-04 19:13:19,2017-10-23 18:21:09,2017-11-01,boleto,43.29,1,9ebfbbb1a5a173f758cb76d6ecc75f9b,d12c926d74ceff0a90a21184466ce161,2017-10-11 02:56:32,26.50,16.79
31209,f80ad99e797d6ae86865bed1ff9483dc,56f782fa47a9dd4a8afbd385ac3a8061,delivered,2017-12-31 16:52:58,2017-12-31 17:07:34,2018-01-02 16:49:03,2018-01-11 19:48:47,2018-01-18,credit_card,29.33,1,f0bbc1bdaf90ddcab4aa862660dfc6d3,f262cbc1c910c83959f849465454ddd3,2018-01-05 17:07:34,19.99,9.34
88001,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [353]:
merged_orders_payments_orderItems[merged_orders_payments_orderItems['order_id'] == "8272b63d03f5f79c56e9e4120aec44ef"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
78584,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,1,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78585,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,2,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78586,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,3,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78587,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,4,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78588,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,5,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78589,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,6,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78590,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,7,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78591,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,8,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78592,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,9,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78593,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,10,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78594,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,11,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78595,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,12,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78596,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,13,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78597,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,14,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78598,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,15,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78599,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,16,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78600,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,17,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78601,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,18,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78602,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,19,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78603,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
78604,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.8,6.57

In [354]:
merged_orders_payments_orderItems.groupby(["order_id", "customer_id", ]).sum("payment_value")

,,payment_value,order_item_id,price,freight_value
order_id,customer_id,,,,
00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,58.90,13.29
00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,239.90,19.93
000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,199.00,17.87
00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,199.90,18.14
00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,31.75,1,19.90,11.85
...,...,...,...,...,...
fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,1427.04,10,220.00,136.76
fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,139.88,1,119.85,20.03
fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,343.40,1,299.99,43.41
fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,386.53,1,350.00,36.53
fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,55.79,1,43.00,12.79

In [355]:
merged_orders_payments_orderItems.drop(columns=['order_item_id'], inplace=True)

/var/folders/xh/dlr59jp10wj5hx57q_rhfy3c0000gn/T/ipykernel_12706/3708324247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_orders_payments_orderItems.drop(columns=['order_item_id'], inplace=True)

In [356]:
merged_orders_payments_orderItems.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [357]:
merged_orders_payments_orderItems = merged_orders_payments_orderItems.groupby(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date']).agg(price=("price", "sum"),
                                    freight_value=("freight_value", "sum"),
                                      Quantity=("product_id", "count")).reset_index()

In [358]:
merged_orders_payments_orderItems

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,credit_card,72.19,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,1
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,credit_card,259.83,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,1
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,credit_card,216.87,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,1
3,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,credit_card,218.04,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,1
4,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,credit_card,31.75,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80151,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,boleto,356.76,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,220.00,136.76,4
80152,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,delivered,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23,credit_card,139.88,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03,1
80153,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,boleto,343.40,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,1
80154,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,boleto,386.53,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1
80155,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,credit_card,55.79,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,1

In [359]:
merged_orders_payments_orderItems[merged_orders_payments_orderItems['order_id'] == '9287e4565306ec8435df6a40c6f481ac']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
45670,9287e4565306ec8435df6a40c6f481ac,f4cf791c1b6a500f0140aa4cb7503f8b,delivered,2017-08-29 22:51:26,2017-08-29 23:06:23,2017-08-30 13:35:54,2017-09-12 16:53:53,2017-09-26,credit_card,11.78,e38e0b558340e87a62ebeacc7b83d8d7,dbb9b48c841a0e39e21f98e1a6b2ec3e,2017-09-04 23:06:23,44.99,16.79,1
45671,9287e4565306ec8435df6a40c6f481ac,f4cf791c1b6a500f0140aa4cb7503f8b,delivered,2017-08-29 22:51:26,2017-08-29 23:06:23,2017-08-30 13:35:54,2017-09-12 16:53:53,2017-09-26,voucher,50.00,e38e0b558340e87a62ebeacc7b83d8d7,dbb9b48c841a0e39e21f98e1a6b2ec3e,2017-09-04 23:06:23,44.99,16.79,1

In [360]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [361]:
merged_orders_payments_orderItems.loc[np.where(round((merged_orders_payments_orderItems['price'] + merged_orders_payments_orderItems['freight_value']), 2) > merged_orders_payments_orderItems['payment_value'])].sort_values(by='order_id', ascending=False).head(50)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
80047,ffa39020fe7c8a3e907320e1bec4b985,26978239b9a0ccb40d576a0a099158b0,delivered,2017-10-31 18:34:34,2017-10-31 19:34:38,2017-11-03 23:57:43,2017-11-21 20:41:55,2017-11-28,voucher,64.01,9e0e152552a1323f7e5dcf63d50cdae3,cc419e0650a3c5ba77189a1882b7556a,2017-11-10 18:55:13,56.99,14.15,1
80046,ffa39020fe7c8a3e907320e1bec4b985,26978239b9a0ccb40d576a0a099158b0,delivered,2017-10-31 18:34:34,2017-10-31 19:34:38,2017-11-03 23:57:43,2017-11-21 20:41:55,2017-11-28,credit_card,7.13,9e0e152552a1323f7e5dcf63d50cdae3,cc419e0650a3c5ba77189a1882b7556a,2017-11-10 18:55:13,56.99,14.15,1
79998,ff7400d904161b62b6e830b3988f5cbd,11eee0e62a0b905cf878ff13c8aec4a0,delivered,2018-03-27 15:37:03,2018-03-27 15:51:53,2018-04-11 01:05:20,2018-04-25 16:32:06,2018-05-07,voucher,100.00,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2018-04-10 15:51:53,116.99,37.97,1
79997,ff7400d904161b62b6e830b3988f5cbd,11eee0e62a0b905cf878ff13c8aec4a0,delivered,2018-03-27 15:37:03,2018-03-27 15:51:53,2018-04-11 01:05:20,2018-04-25 16:32:06,2018-05-07,credit_card,54.96,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2018-04-10 15:51:53,116.99,37.97,1
79900,ff20ee702706d9e407a34de9fe2ff768,0499e8d702425ef8b10da2172f9fec96,delivered,2018-03-28 12:11:45,2018-03-28 12:27:54,2018-03-29 20:28:58,2018-04-05 23:31:56,2018-04-17,voucher,50.00,7b1f55eb9b85b0aa6b1d4c16108eac61,1e8b33f18b4f7598d87f5cbee2282cc2,2018-04-03 12:27:54,159.90,22.20,1
79899,ff20ee702706d9e407a34de9fe2ff768,0499e8d702425ef8b10da2172f9fec96,delivered,2018-03-28 12:11:45,2018-03-28 12:27:54,2018-03-29 20:28:58,2018-04-05 23:31:56,2018-04-17,credit_card,132.10,7b1f55eb9b85b0aa6b1d4c16108eac61,1e8b33f18b4f7598d87f5cbee2282cc2,2018-04-03 12:27:54,159.90,22.20,1
79897,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,delivered,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,voucher,246.89,e7a6f33d382bca6fa19f52ff13e440bd,4a3ca9315b744ce9f8e9374361493884,2017-08-16 16:25:17,222.00,36.06,3
79896,ff1f8f328e5a59ac754240b6dd31bcb4,ba53e87622e90e0a905d871c0c8d53af,delivered,2017-08-10 16:07:21,2017-08-10 16:25:17,2017-08-14 20:59:59,2017-08-19 14:17:43,2017-08-30,credit_card,11.17,e7a6f33d382bca6fa19f52ff13e440bd,4a3ca9315b744ce9f8e9374361493884,2017-08-16 16:25:17,222.00,36.06,3
79864,ff027db47fd74b1bcf2dd6c24f0b809e,951cca7b29b84f6f11fa7856a19544ed,delivered,2017-08-18 22:10:07,2017-08-18 22:25:21,2017-08-22 13:40:07,2017-08-31 19:20:50,2017-09-13,voucher,89.64,697b581688dd771021a47554cbff8f94,8581055ce74af1daba164fdbd55a40de,2017-08-24 22:25:21,98.00,21.53,1
79863,ff027db47fd74b1bcf2dd6c24f0b809e,951cca7b29b84f6f11fa7856a19544ed,delivered,2017-08-18 22:10:07,2017-08-18 22:25:21,2017-08-22 13:40:07,2017-08-31 19:20:50,2017-09-13,credit_card,29.89,697b581688dd771021a47554cbff8f94,8581055ce74af1daba164fdbd55a40de,2017-08-24 22:25:21,98.00,21.53,1
79852,fefbe15ebcd87ab3fb8577e635a8b31c,d3b38af3b96edca0fb37ce0da53bfd3c,delivered,2018-03-08 21:11:34,2018-03-08 21:28:16,2018-03-19 19:11:47,2018-03-20 20:14:01,2018-03-20,voucher,19.90,380db7678ce8fd2e3c80de130bc32fbd,9539213aa8e023c01937bef95dc006da,2018-03-14 21:28:16,19.90,8.29,1
79851,fefbe15ebcd87ab3fb8577e635a8b31c,d3b38af3b96edca0fb37ce0da53bfd3c,delivered,2018-03-08 21:11:34,2018-03-08 21:28:16,2018-03-19 19:11:47,2018-03-20 20:14:01,2018-03-20,credit_card,8.29,380db7678ce8fd2e3c80de130bc32fbd,9539213aa8e023c01937bef95dc006da,2018-03-14 21:28:16,19.90,8.29,1
79847,fef89b64a9e94a0533f8c0afa152f524,10f2f23370c003742306e23361255df0,delivered,2018-03-16 11:30:55,2018-03-16 11:49:11,2018-03-19 21:46:37,2018-04-09 18:16:35,2018-04-05,credit_card,11.71,6d7d853286dac8449c42146f8ce5dedf,3be634553519fb6536a03e1358e9fdc7,2018-03-22 11:49:11,18.50,12.79,1
79848,fef89b64a9e94a0533f8c0afa152f524,10f2f23370c003742306e23361255df0,delivered,2018-03-16 11:30:55,2018-03-16 11:49:11,2018-03-19 21:46:37,2018-04-09 18:16:35,2018-04-05,voucher,19.58,6d7d853286dac8449c42146f8ce5dedf,3be634553519fb6536a03e1358e9fdc7,2018-03-22 11:49:11,18.50,12.79,1
79804,fedcd9f7ccdc8cba3a18defedd1a5547,13aa59158da63ba0e93ec6ac2c07aacb,delivered,2017-09-23 14:56:45,2017-09-25 17:44:41,2017-10-02 23:47:54,2017-10-18 22:35:50,2017-10-23,voucher,204.07,0554911df28fda9fd668ce5ba5949695,7c67e1448b00f6e969d365cea6b010ab,2017-10-05 17:44:41,159.98,45.76,2
79803,fedcd9f7ccdc8cba3a18defedd1a5547,13aa59158da63ba0e93ec6ac2c07aacb,delivered,2017-09-23 14:56:45,2017-09-25 17:44:41,2017-10-02 23:47:54,2017-10-18 22:35:50,2017-10-23,credit_card,1.67,0554911df28fda9fd668ce5ba5949695,7c67e1448b00f6e969d365cea6b010ab,2017-10-05 17:44:41,159.98,45.76,2
79778,fec5c44b191dacb759c39338c8c934a0,6f876d87bb2552c9b2063e96228ec5cd,delivered,2017-11-20 13:13:45,2017-11-22 15:47:22,2017-11-23 17:56:53,2017-12-27 19:22:45,2017-12-13,voucher,69.16,22c5ddc22ea8cae84fc9917def682dc6,cc419e0650a3c5ba77189a1882b7556a,2017-12-01 15:46:52,56.99,15.15,1
79777,fec5c44b191dacb759c39338c8c934a0,6f876d87bb2552c9b2063e96228ec5cd,delivered,2017-11-20 13:13:45,2017-11-22 15:47:22,2017-11-23 17:56:53,2017-12-27 19:22:45,2017-12-13,credit_card,2.98,22c5ddc22ea8cae84fc9917def682dc6,cc419e0650a3c5ba77189a1882b7556a,2017-12-01 15:46:52,56.99,15.15,1
79771,fec086a14f64723dead262e2bfba3284,90c561d8222ed24ce3e23902f137a520,delivered,2018-06-12 10:41:26,2018-06-12 11:00:39,2018-06-13 14:13:00,2018-06-21 17:28:50,2018-07-12,voucher,100.00,045da764883d50dc071cc70c81226cbc,d921b68bf747894be13a97ae52b0f386,2018-06-14 11:00:39,239.00,23.60,1
79770,fec086a14f64723dead262e2bfba3284,90c561d8222ed24ce3e23902f137a520,delivered,2018-06-12 10:41:26,2018-06-12 11:00:39,2018-06-13 14:13:00,2018-06-21 17:28:50,2018-07-12,credit_card,162.60,045da764883d50dc071cc70c81226cbc,d921b68bf747894be13a97ae52b0f386,2018-06-14 11:00:39,239.00,23.60,1
79688,fe716cfce373a25b4ceadf7e5d410b0c,6a156870c25beee81fa1374d048c5055,delivered,2018-03-25 00:06:05,2018-03-26 09:55:29,2018-04-03 19:41:30,2018-04-24 17:21:07,2018-04-17,voucher,25.05,0ecb699933e1e9cc336bf7569ad72e84,cac4c8e7b1ca6252d8f20b2fc1a2e4af,2018-03-30 09:55:29,19.99,17.93,1
79687,fe716cfce373a25b4ceadf7e5d410b0c,6a156870c25beee81fa1374d048c5055,delivered,2018-03-25 00:06:05,2018-03-26 09:55:29,2018-04-03 19:41:30,2018-04-24 17:21:07,2018-04-17,credit_card,12.87,0ecb699933e1e9cc336bf7569ad72e84,cac4c8e7b1ca6252d8f20b2fc1a2e4af,2018-03-30 09:55:29,19.99,17.93,1
79653,fe583f15d230c8ef63b9c1e8053a5240,b8203436dd3a41276d7be98831ddd3f1,delivered,2017-10-29 11:59:16,2017-10-29 12:10:20,2017-10-31 20:35:35,2017-11-13 17:37:39,2017-11-30,voucher,20.00,1510ee95ef047969c335bac927d99bc4,38e6dada03429a47197d5d584d793b41,2017-11-03 12:10:20,18.42,22.67,1
79652,fe583f15d230c8ef63b9c1e8053a5240,b8203436dd3a41276d7be98831ddd3f1,delivered,2017-10-29 11:59:16,2017-10-29 12:10:20,2017-10-31 20:35:35,2017-11-13 17:37:39,2017-11-30,credit_card,21.09,1510ee95ef047969c335bac927d99bc4,38e6dada03429a47197d5d584d793b41,2017-11-03 12:10:20,18.42,22.67,1
79556,fdff9c6a7acb0e02d1cea8d18811e251,eddc5297a74164ee82529b15e8357af7,delivered,2018-06-19 14:10:30,2018-06-19 14:37:39,2018-06-20 13:03:00,2018-06-21 19:03:20,2018-06-29,voucher,230.77,936a034fe3b07b7ae7c87fc8ceb0749d,6560211a19b47992c3666cc44a7e94c0,2018-06-21 14:31:59,249.00,9.90,1
79555,fdff9c6a7acb0e02d1cea8d18811e251,eddc5297a74164ee82529b15e8357af7,delivered,2018-06-19 14:10:30,2018-06-19 14:37:39,2018-06-20 13:03:00,2018-06-21 19:03:20,2018-06-29,credit_card,28.13,936a034fe3b07b7ae7c87fc8ceb0749d,6560211a19b47992c3666cc44a7e94c0,2018-06-21 14:31:59,249.00,9.90,1
79477,fdcafe63dae6994927f09336202f66ea,da338d46857a5eb4eef98d487b841137,delivered,2018-06-10 23:08:53,2018-06-10 23:37:33,2018-06-11 13:03:00,2018-06-20 17:52:08,2018-07-12,voucher,50.43,88d1ed18fd38fa0ffeeb4b517ca42a9d,594f9aaa48e5bf431f011ddc5669b0d5,2018-06-14 23:30:24,36.90,17.06,1
79476,fdcafe63dae6994927f09336202f66ea,da338d46857a5eb4eef98d487b841137,delivered,2018-06-10 23:08:53,2018-06-10 23:37:33,2018-06-11 13:03:00,2018-06-20 17:52:08,2018-07-12,credit_card,3.53,88d1ed18fd38fa0ffeeb4b517ca42a9d,594f9aaa48e5bf431f011ddc5669b0d5,2018-06-14 23:30:24,36.90,17.06,1
79457,fdb64e7a41f724c8b968b87ad729c6ce,b4f0a4587f88d09521775a8b54b7f101,delivered,2017-09-13 16:30:36,2017-09-13 16:44:05,2017-09-15 17:40:09,2017-09-20 22:02:53,2017-10-04,voucher,50.00,75d6b6963340c6063f7f4cfcccfe6a30,cc419e0650a3c5ba77189a1882b7556a,2017-09-20 16:44:05,56.99,15.15,1
79456,fdb64e7a41f724c8b968b87ad729c6ce,b4f0a4587f88d09521775a8b54b7f101,delivered,2017-09-13 16:30:36,2017-09-13 16:44:05,2017-09-15 17:40:09,2017-09-20 22:02:53,2017-10-04,credit_card,22.14,75d6b6963340c6063f7f4cfcccfe6a30,cc419e0650a3c5ba77189a1882b7556a,2017-09-20 16:44:05,56.99,15.15,1
79432,fd9cab205c6b8e485793804e2fdab6fc,5015b446c93382510a9e662ef293c54e,delivered,2018-03-26 10:11:45,2018-03-26 10:27:21,2018-03-27 01:14:34,2018-04-09 21:58:50,2018-04-12,voucher,24.30,38ad86e536a0e27c5a4d2dc30964259d,ea8482cd71df3c1969d7b9473ff13abc,2018-03-30 10:27:21,24.99,12.79,1
79431,fd9cab205c6b8e485793804e2fdab6fc,5015b446c93382510a9e662ef293c54e,delivered,2018-03-26 10:11:45,2018-03-26 10:27:21,2018-03-27 01:14:34,2018-04-09 21:58:50,2018-04-12,credit_card,13.48,38ad86e536a0e27c5a4d2dc30964259d,ea8482cd71df3c1969d7b9473ff13abc,2018-03-30 10:27:21,24.99,12.79,1
79429,fd9b8ed51e5ffedf7a56bea36cc5b6f9,0385c03f2b10a0a50ee72d8e3649a4b3,delivered,2018-03-30 23:11:40,2018-03-30 23:26:57,2018-04-04 20:04:05,2018-04-19 18:03:46,2018-04-27,voucher,100.00,0ef8c1b31d81d6b4453f70a61321f73e,fa1a9dec3a9940c072684a46728bf1fc,2018-04-04 23:26:57,119.90,23.42,1
79428,fd9b8ed51e5ffedf7a56bea36cc5b6f9,0385c03f2b10a0a50ee72d8e3649a4b3,delivered,2018-03-30 23:11:40,2018-03-30 23:26:57,2018-04-04 20:04:05,2018-04-19 18:03:46,2018-04-27,credit_card,43.32,0ef8c1b31d81d6b4453f70a61321f73e,fa1a9dec3a9940c072684a46728bf1fc,2018-04-04 23:26:57,119.90,23.42,1
79401,fd86c80924b4be8fb7f58c4ecc680dae,db76ebd0d51c2b3cc44d84cd6df46336,delivered,2018-03-08 19:37:45,2018-03-08 20:28:42,2018-03-09 18:04:46,2018-03-16 01:30:56,2018-03-27,voucher,89.74,d22bbc02259111e107ee7916637d4791,8d956fec2e4337affcb520f56fd8cbfd,2018-03-14 20:28:42,139.98,25.86,2
79400,fd86c80924b4be8fb7f58c4ecc680dae,db76ebd0d51c2b3cc44d84cd6df46336,delivered,2018-03-08 19:37:45,2018-03-08 20:28:42,2018-03-09 18:04:46,2018-03-16 01:30:56,2018-03-27,credit_card,76.10,d22bbc02259111e107ee7916637d4791,8d956fec2e4337affcb520f56fd8cbfd,2018-03-14 20:28:42,139.98,25.86,2
79395,fd85717bc49c767347b7b46317392d7d,d8daedee5a8e83272a2806c5a4e212a6,delivered,2017-08-15 12:37:15,2017-08-15 14:10:11,2017-08-16 17:04:37,2017-08-29 13:04:56,2017-08-31,voucher,30.00,22c5ddc22ea8cae84fc9917def682dc6,cc419e0650a3c5ba77189a1882b7556a,2017-08-24 14:10:11,56.99,8.72,1
79394,fd85717bc49c767347b7b46317392d7d,d8daedee5a8e83272a2806c5a4e212a6,delivered,2017-08-15 12:37:15,2017-08-15 14:10:11,2017-08-16 17:04:37,2017-08-29 13:04:56,2017-08-31,credit_card,35.71,22c5ddc22ea8cae84fc9917def682dc6,cc419e0650a3c5ba77189a1882b7556a,2017-08-24 14:10:11,56.99,8.72,1
79378,fd79284ba0bd11e560e236f939640143,f722f83d0923ea785b61ed0cbdf0bc3e,delivered,2018-05-30 10:44:23,2018-05-30 10:56:31,2018-06-05 11:50:00,2018-06-13 18:48:50,2018-07-13,voucher,161.18,cef9d587c2c31442c9b95eef617db1f4,822bad9bc42b51213ba522fe87b7ab5d,2018-06-07 10:56:31,216.00,24.44,1
79377,fd79284ba0bd11e560e236f939640143,f722f83d0923ea785b61ed0cbdf0bc3e,delivered,2018-05-30 10:44:23,2018-05-30 10:56:31,2018-06-05 11:50:00,2018-06-13 18:48:50,2018-07-13,credit_card,79.26,cef9d587c2c31442c9b95eef617db1f4,822bad9bc42b51213ba522fe87b7ab5d,2018-06-07 10:56:31,216.00,24.44,1
79288,fd33085945f15975375cd8ec85440511,8071c6018a4f75f2afd849a34708e3a0,delivered,2018-08-20 19:34:29,2018-08-20 19:50:41,2018-08-21 11:10:00,2018-08-25 15:08:29,2018-09-04,credit_card,212.82,cdb2152dbfd2aba4877dec3532c819e7,ce69a8021d18961dd2a40269b7c2c293,2018-08-22 19:50:11,217.99,16.63,1
79243,fd1272ba40a94a5fbc6e9548a8486867,2bfd566c10ff41c47dc6e2f9dd51b467,delivered,2017-11-01 09:57:54,2017-11-09 15:15:38,2017-11-10 22:26:35,2017-11-24 16:43:29,2017-12-01,boleto,74.59,f343690217692891e7a092d5c1e5eef7,7178f9f4dd81dcef02f62acdf8151e01,2017-11-21 15:15:38,57.80,16.80,2
79241,fd10deeb9842f5c285152824f810fc08,ac9f629ac1b9ac8a765332bcfaa0f99c,delivered,2017-05-08 19:54:09,2017-05-08 20:10:17,2017-05-10 10:04:33,2017-05-22 17:39:33,2017-06-05,voucher,65.77,bbaef2eadf31fe3ea6702077398be06c,cc419e0650a3c5ba77189a1882b7556a,2017-05-15 20:10:17,56.99,14.15,1
79240,fd10deeb9842f5c285152824f810fc08,ac9f629ac1b9ac8a765332bcfaa0f99c,delivered,2017-05-08 19:54:09,2017-05-08 20:10:17,2017-05-10 10:04:33,2017-05-22 17:39:33,2017-06-05,credit_card,5.37,bbaef2eadf31fe3ea6702077398be06c,cc419e0650a3c5ba77189a1882b7556a,2017-05-15 20:10:17,56.99,14.15,1
79201,fcf9b8fad0bf8c9ebbe6ac43a434d0d9,38488c59ca50203c33c42971cb795edb,delivered,2017-08-04 11:17:00,2017-08-04 11:30:14,2017-08-14 15:58:16,2017-08-28 20:07:31,2017-09-05,voucher,2.27,a8115d34a4b7b74388da609692162c37,85d9eb9ddc5d00ca9336a2219c97bb13,2017-08-10 11:30:14,31.90,21.15,1
79200,fcf9b8fad0bf8c9ebbe6ac43a434d0d9,38488c59ca50203c33c42971cb795edb,delivered,2017-08-04 11:17:00,2017-08-04 11:30:14,2017-08-14 15:58:16,2017-08-28 20:07:31,2017-09-05,credit_card,50.78,a8115d34a4b7b74388da609692162c37,85d9eb9ddc5d00ca9336a2219c97bb13,2017-08-10 11:30:14,31.90,21.15,1
79150,fccf0d3397491d555ae0d9a4689bfc29,b4eb3f1d026daac5c6876d4902bd4773,delivered,2018-01-15 17:45:56,2018-01-15 17:53:27,2018-01-18 14:33:12,2018-02-01 21:12:34,2018-02-07,voucher,99.98,566d15b940c0d5e7a0a37c82b8ce353f,de23c3b98a88888289c6f5cc1209054a,2018-01-19 17:53:27,129.90,15.67,1
79149,fccf0d3397491d555ae0d9a4689bfc29,b4eb3f1d026daac5c6876d4902bd4773,delivered,2018-01-15 17:45:56,2018-01-15 17:53:27,2018-01-18 14:33:12,2018-02-01 21:12:34,2018-02-07,credit_card,45.59,566d15b940c0d5e7a0a37c82b8ce353f,de23c3b98a88888289c6f5cc1209054a,2018-01-19 17:53:27,129.90,15.67,1
79076,fc965b1e986dea6cd20ac94c50878a75,b04f3618968faccdf40501b5798e66bc,delivered,2017-11-24 19:40:07,2017-11-24 22:39:23,2017-11-28 00:03:46,2017-12-22 18:48:01,2017-12-19,voucher,41.71,4e3218a8ef98e65fece172834193d05e,1da3aeb70d7989d1e6d9b0e887f97c23,2017-11-29 22:39:23,59.99,15.17,1
79075,fc965b1e986dea6cd20ac94c50878a75,b04f3618968faccdf40501b5798e66bc,delivered,2017-11-24 19:40:07,2017-11-24 22:39:23,2017-11-28 00:03:46,2017-12-22 18:48:01,2017-12-19,credit_card,33.45,4e3218a8ef98e65fece172834193d05e,1da3aeb70d7989d1e6d9b0e887f97c23,2017-11-29 22:39:23,59.99,15.17,1

In [362]:
merged_orders_payments_orderItems.loc[np.where(round((merged_orders_payments_orderItems['price'] + merged_orders_payments_orderItems['freight_value']), 2) > merged_orders_payments_orderItems['payment_value'])].index

Index([   25,    26,   162,   163,   197,   198,   213,   214,   221,   222,
       ...
       79863, 79864, 79896, 79897, 79899, 79900, 79997, 79998, 80046, 80047],
      dtype='int64', length=3587)

In [363]:
to_remove = merged_orders_payments_orderItems.loc[np.where(round((merged_orders_payments_orderItems['price'] + merged_orders_payments_orderItems['freight_value']), 2) > merged_orders_payments_orderItems['payment_value'])].index

In [364]:
merged_orders_payments_orderItems.drop(to_remove, inplace=True)

In [365]:
merged_orders_payments_orderItems.reset_index(drop=True, inplace=True)

In [366]:
merged_orders_payments_orderItems.sort_values(by='order_id', ascending=False).head(100)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
76568,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,credit_card,55.79,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,1
76567,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,boleto,386.53,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1
76566,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,boleto,343.40,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,1
76565,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,delivered,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23,credit_card,139.88,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03,1
76564,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,boleto,356.76,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,220.00,136.76,4
76563,fffb2ef8874127f75b52b643880fd7e0,ca8374c00203cec663bc1eabf0aaede4,delivered,2018-03-30 15:36:49,2018-04-03 05:08:33,2018-04-03 15:12:19,2018-04-16 16:56:38,2018-04-27,boleto,39.96,ebceb9726cf5c6187b48e17fe58747b0,609e1a9a6c2539919b8205cf7c4e6ff0,2018-04-09 05:08:33,17.90,22.06,1
76562,fffb0b1a50e65c449020434fa835e078,46b385c6d972b73cbcf797a8b16c072d,delivered,2017-04-12 16:35:43,2017-04-12 16:45:12,2017-04-27 09:26:54,2017-05-17 11:38:22,2017-05-15,credit_card,15.86,e7be84ea9462aac5e2b0b08eb35ba7f1,36a968b544695394e4e9d7572688598f,2017-04-28 16:45:12,4.90,10.96,1
76561,fffa82886406ccf10c7b4e35c4ff2788,a5201e1a6d71a8d21e869151bd5b4085,delivered,2017-12-18 16:33:07,2017-12-18 17:33:04,2017-12-20 18:55:00,2018-01-08 18:23:10,2018-01-24,credit_card,273.92,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.90,44.02,1
76560,fff8287bbae429a99bb7e8c21d151c41,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:45,2018-03-17 12:29:22,2018-03-21 19:22:25,2018-04-07 10:07:48,2018-04-19,credit_card,456.28,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,360.00,96.28,2
76559,fff7c4452f050315db1b3f24d9df5fcd,dec8952e97ef6124259c56914fb3569c,delivered,2017-06-01 16:53:03,2017-06-01 17:05:23,2017-06-02 11:49:53,2017-06-08 13:04:40,2017-06-26,credit_card,756.91,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.00,20.91,1
76558,fff6b8ca971f8e3ec822e99d0f2d3d21,2aec499f94f5e82786629a84b816ffb9,delivered,2017-09-15 11:44:46,2017-09-15 12:04:29,2017-09-18 16:47:13,2017-09-21 19:34:19,2017-10-04,credit_card,215.83,9afaad66aca8b0c79e4f084a89c9c92b,42bde9fef835393bb8a8849cb6b7f245,2017-09-21 12:04:29,199.00,16.83,1
76557,fff60e5408a9dd1e92ee30023052af30,3bd40b3dddcb1d27d1068ff0a1f95078,delivered,2018-01-30 10:30:33,2018-01-30 10:55:55,2018-02-06 18:53:12,2018-02-08 15:17:43,2018-02-21,credit_card,148.70,1a405418406359cc2b8815f93bf359c2,4d6d651bd7684af3fffabd5f08d12e5a,2018-02-05 10:55:55,129.90,18.80,1
76556,fff3983dfa3c5a0d752d8d17baa406a0,46930ec4a8599d1436787e37f36161d9,delivered,2018-07-14 21:56:14,2018-07-14 22:05:13,2018-07-17 12:23:00,2018-07-27 16:28:51,2018-08-01,credit_card,80.44,092be1e8336fc404c57bd5970d056886,cbd996ad3c1b7dc71fd0e5f5df9087e2,2018-07-16 22:05:13,66.39,14.05,1
76555,fff2e9e3aa8644e19710216b4ef53ab2,3aa733464591b63ba16abe084903a511,delivered,2017-05-25 17:22:57,2017-05-26 02:42:42,2017-05-26 16:12:47,2017-06-06 14:05:37,2017-06-19,boleto,86.15,7340a3839a1de1e99d149b8cf052a2ec,4a3ca9315b744ce9f8e9374361493884,2017-06-01 02:42:42,69.90,16.25,1
76554,fff2cdc825f9fc0ba3c04227cfa02303,9c18c06ccf9b2fafcc5f956c5b145212,delivered,2018-02-02 10:28:41,2018-02-03 02:52:42,2018-02-08 00:26:55,2018-03-12 17:08:53,2018-03-06,boleto,50.62,044f05bc9de36e8a693a83e4bc79dd0d,ea8482cd71df3c1969d7b9473ff13abc,2018-02-08 02:52:42,24.99,25.63,1
76553,fff1e3e76b816bfe8ef16678cc53c643,e194b91a5dac87c84cc54a7ed3fdad7a,delivered,2018-02-27 08:35:05,2018-02-27 09:08:53,2018-03-02 20:04:21,2018-03-07 14:49:33,2018-03-26,credit_card,86.85,2e910736c31392d46841f315e9511405,7a67c85e85bb2ce8582c35f2203ad736,2018-03-05 09:08:53,65.99,20.86,1
76552,ffefb169ddf34cecc0622a6d3cc387f8,b607e077c8906af72c47a8554a26bc05,delivered,2017-07-02 19:22:03,2017-07-02 19:35:09,2017-07-03 15:21:43,2017-07-19 16:36:31,2017-07-14,credit_card,142.10,601a360bd2a916ecef0e88de72a6531a,7a67c85e85bb2ce8582c35f2203ad736,2017-07-06 19:35:09,129.99,12.11,1
76551,ffef9e1de5dd07b397b373f9bb72cccf,f46860fe1b54585612e3fffdbf52e43a,delivered,2018-01-11 10:02:13,2018-01-11 10:14:27,2018-01-15 22:34:16,2018-02-06 01:05:12,2018-02-09,credit_card,115.50,30ac6df06dc59ad72cf2f158fc2d904c,0dd184061fb0eaa7ca37932c68ab91c5,2018-01-17 10:14:27,94.00,21.50,1
76550,ffef98cd5ecdc992fefbd967549520dd,8219ed06f16d11e061ca521bbc175c17,delivered,2017-06-28 21:01:06,2017-06-30 03:15:21,2017-06-30 14:09:00,2017-07-14 16:19:41,2017-07-20,boleto,153.01,11fd9d7ba552e1d28872e008acf1e050,cb8bcce248bb1fb274ba762d8b971456,2017-07-06 03:15:21,139.90,13.11,1
76549,ffeeb911d070bea3dd20bd5fd01da5e8,c580ed6ed2fe3533df6af1dcb43bac94,delivered,2017-10-06 19:10:16,2017-10-06 19:25:54,2017-10-20 18:15:59,2017-10-25 18:17:06,2017-10-30,credit_card,95.69,a5341e3f8155dbb3e62323d3ea289729,ff063b022a9a0aab91bad2c9088760b7,2017-10-13 19:25:54,79.50,16.19,1
76548,ffee31fb4b5e35c9123608015637c495,11e0f43ab4e2d2c48348dd9332c0ef80,delivered,2018-08-18 10:00:59,2018-08-18 10:10:11,2018-08-20 10:01:00,2018-08-21 12:18:57,2018-08-23,credit_card,112.52,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.00,13.52,1
76547,ffed7e90414c1477a6b92554661d465f,b7a530c512ca7de885521441884f4ef5,delivered,2017-07-31 14:44:31,2017-07-31 14:55:20,2017-08-03 17:27:39,2017-08-14 15:52:37,2017-08-22,credit_card,166.71,550dc4417c636abc04c71404342de695,25c5c91f63607446a97b143d2d535d31,2017-08-04 14:55:20,149.90,16.81,1
76546,ffecd5a79a0084f6a592288c67e3c298,8afa5a415d65a08e3a68b1d7f9ddd8a5,delivered,2018-02-27 20:00:25,2018-02-27 20:15:27,2018-02-28 20:54:52,2018-03-29 14:37:05,2018-03-22,credit_card,113.07,50fd2b788dc166edd20512370dac54df,8b321bb669392f5163d04c59e235e066,2018-03-05 20:15:27,65.70,47.37,3
76545,ffec1a6d35149778ec575d5048d44db8,970ca115b43314d95949db28ed73aa78,delivered,2018-03-20 12:47:53,2018-03-22 02:49:46,2018-03-27 17:06:34,2018-03-28 18:54:28,2018-04-02,boleto,55.04,437c05a395e9e47f9762e677a7068ce7,f84fa566034f5e8e880a07ec624c56af,2018-03-28 02:49:46,47.65,7.39,1
76544,ffebd80e3291e811c308365936897efd,050309b91cc5e04e68841938e7984aaf,delivered,2018-07-13 20:04:05,2018-07-13 20:23:55,2018-07-17 10:03:00,2018-07-23 19:44:45,2018-08-07,credit_card,181.10,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.90,51.20,1
76543,ffea79d8c5fecc22cbff0c54eda9b65c,bbef00095c712ca0e62584d68cb9fdfa,delivered,2017-09-03 17:18:58,2017-09-05 04:24:39,2017-09-06 12:51:23,2017-09-19 21:22:28,2017-10-02,boleto,69.59,ea44caac707f7f1325182a538007f838,855668e0971d4dfd7bef1b6a4133b41b,2017-09-12 04:24:39,50.00,19.59,1
76542,ffea5b26be781da4c215c0feb484f4fd,cefc16cdcbd69d1ea047f70227cd2927,delivered,2017-06-02 16:53:20,2017-06-02 17:05:17,2017-06-06 13:51:15,2017-06-28 07:09:55,2017-06-29,credit_card,140.07,ac23312b29784c30304f2ec719891690,066a6914e1ebf3ea95a216c73a986b91,2017-06-08 17:05:17,119.99,20.08,1
76541,ffea406a848c8afe4dec22bf6290ba00,e85ff8cc3cc2c09bdb9204dd7930c0fb,delivered,2017-03-15 17:16:36,2017-03-15 17:16:36,2017-03-16 12:54:46,2017-04-05 18:48:06,2017-04-05,boleto,162.10,801a695ff5c0c14970a71a4ceb70989e,48162d548f5b1b11b9d29d1e01f75a61,2017-03-21 17:16:36,146.90,15.20,1
76540,ffea20c7630343a6cd9e09858c1295cd,79e8c1737d903a4055c4d2aa87661bf7,delivered,2018-05-23 23:33:30,2018-05-23 23:54:50,2018-05-25 07:10:00,2018-06-04 17:58:36,2018-06-20,credit_card,163.24,3dd2a17168ec895c781a9191c1e95ad7,de722cd6dad950a92b7d4f82673f8833,2018-05-27 23:54:50,149.90,13.34,1
76539,ffe8851012fcdaf83de7b595fd5154b3,decaeb61687071ee0fb5a7863b398032,delivered,2018-02-11 18:48:28,2018-02-11 19:07:46,2018-02-14 21:24:10,2018-02-27 02:13:48,2018-03-09,credit_card,171.84,acc78c9d340dbe682491c9d31ea7e187,7ea5bfa6c340f58f8e71fc1f0412b0d6,2018-02-15 19:07:46,149.99,21.85,1
76538,ffe73fc1d73e03fdb50e63903ddfe882,3f72fbdbb59d2b6db3637e39f881b6fa,delivered,2018-04-17 12:59:40,2018-04-17 13:15:15,2018-04-18 23:18:28,2018-04-26 23:22:32,2018-05-17,credit_card,112.90,53b36df67ebb7c41585e8d54d6772e08,4869f7a5dfa277a7dca6462dcf3b52b2,2018-04-23 13:15:15,112.90,0.00,1
76537,ffe63ac8de50ca1b8d8aba30d6bff4fb,71b497960cffaf0689ae433028997745,delivered,2018-01-02 13:57:36,2018-01-02 14:31:54,2018-01-04 16:43:22,2018-01-08 22:37:58,2018-01-30,credit_card,52.59,fda6a1e500285956c972ec2fe10f4923,751bdc4d83a466c7206cd42e8f426b03,2018-01-08 14:31:54,35.99,16.60,1
76536,ffe5736050c2890fa51a28942820258a,bdb02eddf9e1223ae4fa0cbe08f89cbf,delivered,2018-03-18 14:25:04,2018-03-18 14:35:25,2018-03-28 19:29:49,2018-03-31 11:48:25,2018-04-16,credit_card,94.54,3eef0cb94ba82de806bb30ab743c7655,7c67e1448b00f6e969d365cea6b010ab,2018-03-30 14:35:25,79.99,14.55,1
76535,ffe4b41e99d39f0b837a239110260530,08013618897a5ba0b56ecd80981470da,delivered,2017-08-31 21:15:02,2017-08-31 21:25:40,2017-09-01 15:47:26,2017-09-11 20:57:51,2017-09-22,credit_card,69.58,e97df839917a6e93404867b1d0319bfc,42bde9fef835393bb8a8849cb6b7f245,2017-09-07 21:25:40,38.00,31.58,2
76534,ffe4972089425f7752aad086a7fdce28,bb22cafe10da65775931fd4dfcc38328,delivered,2017-08-23 14:30:58,2017-08-23 14:55:18,2017-08-24 16:48:27,2017-08-30 17:39:10,2017-09-15,credit_card,161.23,547b95702aec86f05ac37e61d164891c,001cca7ae9ae17fb1caed9dfb1094831,2017-08-29 14:55:18,129.00,32.23,1
76533,ffe49171e120186dcc4c444b55691810,9be83b1a15980ed71eadb4dff917fa29,delivered,2017-03-29 02:00:08,2017-03-29 02:15:36,2017-04-04 14:09:49,2017-04-06 12:35:00,2017-04-18,credit_card,76.85,102cdda7fcf3cb71b5f9d6d2a3e56b58,8931a84a914b3fe9b1ddaa4d704947ca,2017-04-04 02:15:36,68.00,8.85,1
76532,ffe48cb3d8485e0cb0405e21192e592f,c7d443bf742505394e4431d332fa5744,delivered,2018-06-29 18:11:54,2018-06-29 18:30:38,2018-07-02 14:06:00,2018-07-12 14:38:38,2018-08-01,credit_card,147.04,dd44ecaddb22d00c140856b180f5d9b4,54965bbe3e4f07ae045b90b0b8541f52,2018-07-11 18:30:38,119.90,27.14,1
76531,ffe3153dcf1c03911848f64ed557764b,9e73c9ebfd2c3c58898f89e7d0409ea4,delivered,2017-04-10 18:36:47,2017-04-11 03:55:09,2017-04-13 07:56:06,2017-04-20 06:42:41,2017-05-08,boleto,287.21,d41d8cd98f00b204e9800998ecf8427e,066a6914e1ebf3ea95a216c73a986b91,2017-04-17 03:55:09,259.90,27.31,1
76530,ffe311829861d844ad8de0f4d4923692,c472584339fbf78789a1285447d0e42a,delivered,2018-07-22 21:53:45,2018-07-23 12:31:44,2018-07-23 14:25:00,2018-07-26 13:08:36,2018-08-09,credit_card,145.90,80d2404aa74015aa6cd21863642295f7,adbc26658d6c7b4b6219f9d934598091,2018-07-25 11:03:35,109.90,36.00,1
76529,ffe2b9e50ccbd9695f42c906f6d9010c,d8eaef18d54f26637bdd57fb1254bbb6,delivered,2018-03-16 12:02:38,2018-03-16 12:15:33,2018-03-19 12:47:54,2018-03-23 19:52:04,2018-04-10,credit_card,201.37,3488d2ce36e718097c1509444289ef7f,26d8a1c7c75d513045798992ead43aa2,2018-03-22 12:15:33,185.99,15.38,1
76528,ffe1f3d903f7d8189c55f1e52438f593,31f102bb049b4af90fb8b555e921b6d4,delivered,2017-06-17 17:20:47,2017-06-17 17:35:09,2017-06-19 20:03:21,2017-06-26 15:03:35,2017-07-21,credit_card,80.10,8477d691ae21afadfa805681bef3a620,272f092de69afedd4d2969440b37f18f,2017-06-22 17:35:09,64.90,15.20,1
76527,ffe146c862ce518ad378598499bf9204,f813294c06241ae2660aa359c74e1d5f,delivered,2018-06-28 21:44:06,2018-06-28 22:10:03,2018-07-03 13:39:00,2018-07-14 07:04:34,2018-07-26,credit_card,102.49,8ab83b53b9a953395f4f21f0b1a845ef,431050a06a317f2b38168dec3dcd2b46,2018-07-04 22:10:03,83.80,18.69,1
76526,ffdee14e5cab83563d890d93e1d16f74,31a8f6d679715fe19892aef333993c5b,delivered,2017-04-29 09:57:46,2017-05-03 11:15:32,2017-05-04 13:08:35,2017-05-10 05:36:41,2017-05-23,boleto,40.46,44a34214a57dc373dcd80f54c919d006,7008613ea464bad5cb9b83456e1e6a8f,2017-05-09 11:15:32,29.50,10.96,1
76525,ffde92ba447b33a47d1c04d203f10f41,502b5f99cc5ae83a33d23ec900e76a3d,delivered,2017-11-24 12:12:36,2017-11-24 14:13:18,2017-11-27 17:49:45,2017-12-05 17:56:55,2017-12-19,credit_card,304.70,a97cd00f5c1dbfbc7f0f4b6c1032253e,b347677812ea483b0f528eaf8cbc09b7,2017-11-30 14:13:18,278.00,26.70,1
76524,ffdda91cd98d69f6be1cd352e4447b8e,b9b441696ae97a6a6d884f8240949ab7,delivered,2018-06-03 13:43:44,2018-06-03 13:55:16,2018-06-04 13:49:00,2018-06-13 18:56:35,2018-07-11,credit_card,65.13,1ec486885049bbb9b79351d150ed18c4,cab85505710c7cb9b720bceb52b01cee,2018-06-11 13:55:16,49.90,15.23,1
76523,ffdd178654127ccf34a439e8704fecd9,33d0814c9eff200629eb49330ce5c6a3,delivered,2018-03-07 14:07:47,2018-03-07 14:29:47,2018-03-09 01:43:26,2018-04-07 13:16:50,2018-04-04,credit_card,108.61,16b4473e98422039c388f144a0b16f55,4de6e4ba574aa9dfdc824bc44dc47fdd,2018-03-13 14:29:47,69.90,38.71,1
76522,ffdce235aaf8a4e381ba694a4da99221,35da61fea067d2343fcef9efa970944f,delivered,2017-12-25 16:50:02,2017-12-27 06:26:36,2017-12-27 20:47:54,2018-01-03 14:43:31,2018-01-19,credit_card,69.14,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2018-01-03 06:26:36,55.00,14.14,1
76521,ffdc79897a2df4181a299b803765f0cc,4f2c86a6f30d1c9c0d935814141e4f29,delivered,2017-10-28 08:23:18,2017-10-31 03:55:10,2017-11-03 16:27:00,2017-11-09 22:28:27,2017-11-23,boleto,62.01,ec2d43cc59763ec91694573b31f1c29a,1c129092bf23f28a5930387c980c0dfc,2017-11-07 03:55:10,45.90,16.11,1
76520,ffdc5e3279114c523a09296f8fd28331,c1268d9379bcbdb861e57fa5ca4b2107,delivered,2017-02-10 14:49:23,2017-02-10 15:03:37,2017-02-14 14:34:40,2017-03-03 18:04:36,2017-03-15,credit_card,317.79,5e70a4508abd5d19bfe7f110785294c8,328acb143b4a73aad6bee8e734f5d20d,2017-02-14 14:49:23,299.99,17.80,1
76519,ffdc30c0eaeed2e08818c4dad9806292,60ff2959ab18e70859b8ae136c0bea28,delivered,2017-08-11 11:44:12,2017-08-12 02:51:01,2017-08-15 21:08:07,2017-08-28 17:33:06,2017-09-06,boleto,34.00,c3f6113d5b61bc95468432072b27e23d,897060da8b9a21f655304d50fd935913,2017-08-17 02:51:01,18.90,15.10,1
76518,ffdb12bf66b3d0145d09d962745a05f6,621bdee022e2acb3aadf90994fd4e39a,delivered,2017-10-14 19:46:54,2017-10-17 04:15:00,2017-10-20 18:17:56,2017-10-27 16:24:37,2017-11-14,boleto,48.09,38e28b7814d36bc84b972a75dd7c5ce7,aae3bfea055532c57fb453ed3ec80b30,2017-10-23 04:15:00,32.99,15.10,1
76517,ffdab5e1596138d37793566aa1424d0c,58f5f08f888dddeeb13e21d686545c6d,delivered,2017-05-02 07:26:40,2017-05-03 11:33:46,2017-05-04 08:56:25,2017-05-11 09:41:25,2017-05-29,boleto,418.35,f0fad8c5dfa2549bff0ca38e82823cf5,7b0df942f46435babab05d49b744b2c4,2017-05-09 11:31:10,399.85,18.50,1
76516,ffda7f88e6a571a9e73a0c9c778e606d,1ac4870458ef0396d390ffbf31cabd7a,delivered,2017-12-16 00:35:54,2017-12-18 01:31:47,2017-12-18 22:04:40,2017-12-28 18:56:47,2018-01-11,credit_card,51.59,001795ec6f1b187d37335e1c4704762e,8b321bb669392f5163d04c59e235e066,2017-12-22 01:31:38,38.90,12.69,1
76515,ffd9fe7f21106081de852f98c6c78dca,6cbf986a2e2aebe93c7f9ec8e598882f,delivered,2017-12-22 01:50:26,2017-12-23 08:09:39,2017-12-27 19:54:47,2018-01-18 23:09:14,2018-02-07,credit_card,70.63,b1cbf530dc2a793ced8e0768ffcce501,1ca7077d890b907f89be8c954a02686a,2017-12-29 08:09:39,45.00,25.63,1
76514,ffd7f21b9b4ea30d3536d4cadd19fa42,3aa42c09878ea293cacb60290fe10035,delivered,2018-05-16 10:02:45,2018-05-17 03:35:19,2018-05-18 09:45:00,2018-06-05 20:08:46,2018-06-20,boleto,112.38,acf90725a7a1fa2b5f4f0d77da84403b,4391ea5c5990502176a1dcda44a2373d,2018-05-23 03:30:52,95.00,17.38,1
76513,ffd7d6378c4d0df542ece430b2daa777,c3c07d1bdef19401e13207023cd71e72,delivered,2017-12-27 14:15:19,2017-12-27 14:29:25,2017-12-28 22:47:10,2018-01-09 18:34:31,2018-01-24,credit_card,73.15,c32b1155b886162db8e1ec114699a799,1835b56ce799e6a4dc4eddc053f04066,2018-01-03 14:29:25,56.99,16.16,1
76512,ffd6f465cab015b452d398ac1f5d978a,0b5f60cff1a206e0bc33c120b8db0335,delivered,2018-04-23 19:33:08,2018-04-24 17:28:54,2018-04-25 14:07:00,2018-05-03 20:52:40,2018-05-29,credit_card,89.70,fdcf45aa23bb8312ecc0027d6e1ef1c4,113e3a788b935f48aad63e1c41dac1bd,2018-05-03 09:30:37,23.52,66.18,3
76511,ffd6f08f294bfa573e0eeb88d6afb17b,8ef6dd55cbf50f4b0aac10b13beb920f,delivered,2017-11-21 13:33:24,2017-11-21 13:46:45,2017-11-24 19:54:43,2017-12-01 17:53:02,2017-12-12,credit_card,366.80,2a11460730aaa623c8897e343fe38cb3,70a12e78e608ac31179aea7f8422044b,2017-11-30 13:46:45,352.00,14.80,1
76510,ffd5efbd46bbf72ad374862a05ef4c72,486d66df3ef703d001f77632e7fe6bd8,delivered,2017-02-01 18:39:14,2017-02-03 03:35:07,2017-02-08 11:05:23,2017-02-15 14:41:47,2017-03-17,boleto,60.42,8338cef8355d238f43711dcb9c0657b2,cca3071e3e9bb7d12640c9fbe2301306,2017-02-11 18:39:14,45.90,14.52,1
76509,ffd543c2b60842e148a86870dc60e212,1a4eed32aecb25c4c294408905613487,delivered,2018-01-04 12:00:49,2018-01-05 02:35:33,2018-01-15 21:23:17,2018-01-17 20:18:44,2018-02-06,boleto,373.11,b7d94dc0640c7025dc8e3b46b52d8239,9c0e69c7bf2619675bbadf47b43f655a,2018-01-11 02:35:33,175.91,14.15,1
76508,ffd543c2b60842e148a86870dc60e212,1a4eed32aecb25c4c294408905613487,delivered,2018-01-04 12:00:49,2018-01-05 02:35:33,2018-01-15 21:23:17,2018-01-17 20:18:44,2018-02-06,boleto,373.11,3ce943997ff85cad84ec6770b35d6bcd,9c0e69c7bf2619675bbadf47b43f655a,2018-01-11 02:35:33,175.90,7.15,1
76507,ffd4172b5df0c16bbd973c196b09bcd9,df1c081b34ddbb007ef29155a35e0837,delivered,2017-11-16 12:32:53,2017-11-16 12:51:15,2017-11-20 20:16:40,2018-01-05 14:09:44,2017-12-14,credit_card,153.36,58bef3ad35aed45b92cf03510e6cf5ce,c3867b4666c7d76867627c2f7fb22e21,2017-11-22 12:50:42,115.00,38.36,1
76506,ffd3ff583dec4975e6443d6a396f2f36,480b60f05b6caa21bd6edbea402d607b,delivered,2017-11-23 23:04:02,2017-11-23 23:12:31,2017-11-27 16:58:04,2017-12-05 18:07:48,2017-12-22,credit_card,172.09,f00b39a2c66d045f07fdfe7d8ddc4ed9,d91fb3b7d041e83b64a00a3edfb37e4f,2017-11-29 23:12:31,156.25,15.84,1
76505,ffce8a2dd7579795f5c1cbe2bf23d51d,4b80c7d4d1810bb81823061e2d14ed1c,delivered,2018-05-07 21:04:46,2018-05-07 21:15:48,2018-05-09 06:34:00,2018-05-14 12:41:36,2018-05-24,credit_card,126.78,00878d953636afec00d3e85d55a12e7f,955fee9216a65b617aa5c0531780ce60,2018-05-09 21:15:18,100.00,26.78,1
76504,ffce02d92a959d8894c8568d7a0f6435,246fdbb2a404aaee6bb5d93190dbf7e0,delivered,2017-11-07 12:23:54,2017-11-08 03:50:25,2017-11-10 19:34:43,2017-11-22 20:27:36,2017-12-06,boleto,67.02,ace5d86cf1ac63cdb76f49e5cd23d2f8,cca3071e3e9bb7d12640c9fbe2301306,2017-11-14 03:30:56,50.90,16.12,1
76503,ffcbf9b4459704e9185c5c630d11b69c,1e7f26bfc1b72023a4e9b1800f281912,delivered,2017-02-25 07:53:03,2017-02-26 08:01:52,2017-03-02 14:35:13,2017-03-14 09:41:37,2017-03-30,credit_card,137.14,9ae3dacfd2327107a1e28274fac25a4e,0c8380b62e38e8a1e6adbeba7eb9688c,2017-03-02 08:01:52,109.90,27.24,1
76502,ffc97f5975c4aa1b3c9754d83050c73d,2713513e2014d3d6181fd3ed037d4a80,delivered,2018-06-22 00:13:26,2018-06-23 01:40:06,2018-06-27 11:45:00,2018-07-11 23:08:37,2018-08-06,credit_card,190.33,1c4dbd58e9b07007a271122f96bb0add,c33847515fa6305ce6feb1e818569f13,2018-06-28 01:30:35,149.00,41.33,1

In [367]:
merged_orders_payments_orderItems[merged_orders_payments_orderItems['order_id'] == "8272b63d03f5f79c56e9e4120aec44ef"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
38892,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,12.0,78.90,10
38893,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,12.0,78.90,10
38894,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.11,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.8,6.57,1

In [368]:
# this implies, customer_id column is the one to be kept, dropping the customer_unique_id was the right decision
pd.merge(customers, merged_orders_payments_orderItems, left_on='customer_id', right_on='customer_id', how='inner')

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,Franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,credit_card,146.87,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,1
1,18955e83d337fd6b2def6b18a428ac77,9790,Sao Bernardo Do Campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,credit_card,335.48,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48,1
2,4e7b3e00288586ebd08712fdd0374a03,1151,Sao Paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,credit_card,157.73,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,1
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,Mogi Das Cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,credit_card,173.30,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,1
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,Campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,credit_card,252.25,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76564,7fe2e80252a9ea476f950ae8f85b0f8f,35500,Divinopolis,MG,c9aea907527f5d4f5fb44955c18a79fb,delivered,2017-12-17 23:13:41,2017-12-18 00:17:27,2017-12-20 18:52:08,2018-01-04 13:08:05,2018-01-23,credit_card,75.88,c770c3d5ab511e88a96d387bdb0b6ce0,e06f09ec0a4aca210779cf1cfc63cf19,2018-01-03 00:17:27,55.00,20.88,1
76565,17ddf5dd5d51696bb3d7c6291687be6f,3937,Sao Paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25,credit_card,88.78,ccb4503d9d43d245d3b295d0544f988b,527801b552d0077ffd170872eb49683b,2018-04-12 16:08:45,74.90,13.88,1
76566,e7b71a9017aa05c9a7fd292d714858e8,6764,Taboao Da Serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20,credit_card,129.06,9ede6b0570a75a4b9de4f383329f99ee,3fd1e727ba94cfe122d165e176ce7967,2018-04-10 08:35:12,114.90,14.16,1
76567,5e28dfe12db7fb50a4b2f691faecea5e,60115,Fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02,credit_card,56.04,7a5d2e1e131a860ae7d18f6fffa9d689,d9e7e7778b32987280a6f2cb9a39c57d,2018-04-12 20:30:03,37.00,19.04,1
76568,56b18e2166679b8a959d72dd06da27f9,92120,Canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05,credit_card,711.07,f819f0c84a64f02d3a5606ca95edd272,4869f7a5dfa277a7dca6462dcf3b52b2,2017-11-09 21:15:51,689.00,22.07,1

In [369]:
import pandas as pd

In [370]:
reviews = pd.read_csv("../Ecommerce-DataAnalytics/archive (13)/olist_order_reviews_dataset.csv")

In [371]:
reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [372]:
to_remove = reviews[~reviews['order_id'].isin(merged_orders_payments_orderItems['order_id'])].index

In [373]:
reviews.drop(to_remove, inplace = True)

In [374]:
reviews.reset_index(drop=True, inplace=True)

In [375]:
merged_orders_payments_orderItems[merged_orders_payments_orderItems['order_id'].duplicated()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
97,005d9a5423d47281ac463a968b3936fb,a2be07c22a9d2071f65b6770e47f540b,delivered,2017-10-18 12:14:29,2017-10-18 12:28:16,2017-10-24 14:56:52,2017-10-27 19:19:43,2017-11-17,credit_card,145.26,fb7a100ec8c7b34f60cec22b1a9a10e0,d98eec89afa3380e14463da2aabaea72,2017-10-24 12:28:16,49.99,18.12,1
146,00946f674d880be1f188abc10ad7cf46,9583b047c90d4aa1c5c68b4065ba7f4e,delivered,2017-12-09 19:11:22,2017-12-09 19:30:37,2017-12-11 18:47:04,2017-12-17 10:19:09,2018-01-05,credit_card,232.72,9bb2d066e4b33b624cbdfec7d50b3dcb,5cf13accae3222c70a9cac40818ae839,2017-12-14 19:30:37,99.90,14.35,1
154,0097f0545a302aafa32782f1734ff71c,a60b063f8b715db294b889eae5acb4b6,delivered,2018-03-05 18:15:11,2018-03-05 18:30:41,2018-03-06 22:04:03,2018-03-21 18:16:52,2018-03-21,credit_card,507.84,b6397895a17ce86decd60b898b459796,7901646fdd36a55f564ffaf2dbccaaf7,2018-03-09 18:30:41,158.00,10.68,1
203,00bcee890eba57a9767c7b5ca12d3a1b,3cecfffcfcdbac8b85cf74dfc8a60166,delivered,2017-07-22 20:51:26,2017-07-22 21:05:07,2017-07-25 19:12:51,2017-07-27 18:34:12,2017-08-21,credit_card,772.50,6c90c0f6c2d89eb816b9e205b9d6a36a,3bb548e3cb7f70f28e3f11ee9dce0e59,2017-07-26 21:05:07,165.50,15.80,1
204,00bcee890eba57a9767c7b5ca12d3a1b,3cecfffcfcdbac8b85cf74dfc8a60166,delivered,2017-07-22 20:51:26,2017-07-22 21:05:07,2017-07-25 19:12:51,2017-07-27 18:34:12,2017-08-21,credit_card,772.50,b7d94dc0640c7025dc8e3b46b52d8239,9c0e69c7bf2619675bbadf47b43f655a,2017-07-26 21:05:07,175.91,52.69,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76482,ffb8f7de8940249a3221252818937ecb,036a2b2e7d16c12b97890ea51a2ef172,delivered,2018-07-22 12:58:25,2018-07-23 09:04:32,2018-07-23 11:41:00,2018-07-31 15:05:05,2018-08-10,debit_card,245.12,bd0ac51dc93e62c4dbe6ca9d70a9b311,1d4587203296c8f4ad134dc286fa6db0,2018-07-27 09:04:32,64.50,42.47,1
76483,ffb8f7de8940249a3221252818937ecb,036a2b2e7d16c12b97890ea51a2ef172,delivered,2018-07-22 12:58:25,2018-07-23 09:04:32,2018-07-23 11:41:00,2018-07-31 15:05:05,2018-08-10,debit_card,245.12,bd6e8cf9fe4122c385da2bcb9f979d5d,9f50216bfd01913736a55a11b55ea842,2018-07-27 09:04:32,45.00,6.79,1
76485,ffb9a9cd00c74c11c24aa30b3d78e03b,81a0150b8f472d0e5e82a7da198b93bc,delivered,2017-03-11 17:20:21,2017-03-11 17:20:21,2017-03-22 08:48:30,2017-03-28 15:26:02,2017-04-13,credit_card,606.95,3321ad579f19476d0d668f726f8dffec,da8622b14eb17ae2831f4ac5b9dab84a,2017-03-22 17:20:21,219.90,22.18,1
76486,ffb9a9cd00c74c11c24aa30b3d78e03b,81a0150b8f472d0e5e82a7da198b93bc,delivered,2017-03-11 17:20:21,2017-03-11 17:20:21,2017-03-22 08:48:30,2017-03-28 15:26:02,2017-04-13,credit_card,606.95,fec565c4e3ad965c73fb1a21bb809257,da8622b14eb17ae2831f4ac5b9dab84a,2017-03-22 17:20:21,179.80,36.68,2
76509,ffd543c2b60842e148a86870dc60e212,1a4eed32aecb25c4c294408905613487,delivered,2018-01-04 12:00:49,2018-01-05 02:35:33,2018-01-15 21:23:17,2018-01-17 20:18:44,2018-02-06,boleto,373.11,b7d94dc0640c7025dc8e3b46b52d8239,9c0e69c7bf2619675bbadf47b43f655a,2018-01-11 02:35:33,175.91,14.15,1

In [376]:
merged_orders_payments_orderItems[merged_orders_payments_orderItems['order_id'].duplicated()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
97,005d9a5423d47281ac463a968b3936fb,a2be07c22a9d2071f65b6770e47f540b,delivered,2017-10-18 12:14:29,2017-10-18 12:28:16,2017-10-24 14:56:52,2017-10-27 19:19:43,2017-11-17,credit_card,145.26,fb7a100ec8c7b34f60cec22b1a9a10e0,d98eec89afa3380e14463da2aabaea72,2017-10-24 12:28:16,49.99,18.12,1
146,00946f674d880be1f188abc10ad7cf46,9583b047c90d4aa1c5c68b4065ba7f4e,delivered,2017-12-09 19:11:22,2017-12-09 19:30:37,2017-12-11 18:47:04,2017-12-17 10:19:09,2018-01-05,credit_card,232.72,9bb2d066e4b33b624cbdfec7d50b3dcb,5cf13accae3222c70a9cac40818ae839,2017-12-14 19:30:37,99.90,14.35,1
154,0097f0545a302aafa32782f1734ff71c,a60b063f8b715db294b889eae5acb4b6,delivered,2018-03-05 18:15:11,2018-03-05 18:30:41,2018-03-06 22:04:03,2018-03-21 18:16:52,2018-03-21,credit_card,507.84,b6397895a17ce86decd60b898b459796,7901646fdd36a55f564ffaf2dbccaaf7,2018-03-09 18:30:41,158.00,10.68,1
203,00bcee890eba57a9767c7b5ca12d3a1b,3cecfffcfcdbac8b85cf74dfc8a60166,delivered,2017-07-22 20:51:26,2017-07-22 21:05:07,2017-07-25 19:12:51,2017-07-27 18:34:12,2017-08-21,credit_card,772.50,6c90c0f6c2d89eb816b9e205b9d6a36a,3bb548e3cb7f70f28e3f11ee9dce0e59,2017-07-26 21:05:07,165.50,15.80,1
204,00bcee890eba57a9767c7b5ca12d3a1b,3cecfffcfcdbac8b85cf74dfc8a60166,delivered,2017-07-22 20:51:26,2017-07-22 21:05:07,2017-07-25 19:12:51,2017-07-27 18:34:12,2017-08-21,credit_card,772.50,b7d94dc0640c7025dc8e3b46b52d8239,9c0e69c7bf2619675bbadf47b43f655a,2017-07-26 21:05:07,175.91,52.69,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76482,ffb8f7de8940249a3221252818937ecb,036a2b2e7d16c12b97890ea51a2ef172,delivered,2018-07-22 12:58:25,2018-07-23 09:04:32,2018-07-23 11:41:00,2018-07-31 15:05:05,2018-08-10,debit_card,245.12,bd0ac51dc93e62c4dbe6ca9d70a9b311,1d4587203296c8f4ad134dc286fa6db0,2018-07-27 09:04:32,64.50,42.47,1
76483,ffb8f7de8940249a3221252818937ecb,036a2b2e7d16c12b97890ea51a2ef172,delivered,2018-07-22 12:58:25,2018-07-23 09:04:32,2018-07-23 11:41:00,2018-07-31 15:05:05,2018-08-10,debit_card,245.12,bd6e8cf9fe4122c385da2bcb9f979d5d,9f50216bfd01913736a55a11b55ea842,2018-07-27 09:04:32,45.00,6.79,1
76485,ffb9a9cd00c74c11c24aa30b3d78e03b,81a0150b8f472d0e5e82a7da198b93bc,delivered,2017-03-11 17:20:21,2017-03-11 17:20:21,2017-03-22 08:48:30,2017-03-28 15:26:02,2017-04-13,credit_card,606.95,3321ad579f19476d0d668f726f8dffec,da8622b14eb17ae2831f4ac5b9dab84a,2017-03-22 17:20:21,219.90,22.18,1
76486,ffb9a9cd00c74c11c24aa30b3d78e03b,81a0150b8f472d0e5e82a7da198b93bc,delivered,2017-03-11 17:20:21,2017-03-11 17:20:21,2017-03-22 08:48:30,2017-03-28 15:26:02,2017-04-13,credit_card,606.95,fec565c4e3ad965c73fb1a21bb809257,da8622b14eb17ae2831f4ac5b9dab84a,2017-03-22 17:20:21,179.80,36.68,2
76509,ffd543c2b60842e148a86870dc60e212,1a4eed32aecb25c4c294408905613487,delivered,2018-01-04 12:00:49,2018-01-05 02:35:33,2018-01-15 21:23:17,2018-01-17 20:18:44,2018-02-06,boleto,373.11,b7d94dc0640c7025dc8e3b46b52d8239,9c0e69c7bf2619675bbadf47b43f655a,2018-01-11 02:35:33,175.91,14.15,1

In [377]:
merged_orders_payments_orderItems.loc[np.where(merged_orders_payments_orderItems['order_id']=='ffd543c2b60842e148a86870dc60e212')]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
76508,ffd543c2b60842e148a86870dc60e212,1a4eed32aecb25c4c294408905613487,delivered,2018-01-04 12:00:49,2018-01-05 02:35:33,2018-01-15 21:23:17,2018-01-17 20:18:44,2018-02-06,boleto,373.11,3ce943997ff85cad84ec6770b35d6bcd,9c0e69c7bf2619675bbadf47b43f655a,2018-01-11 02:35:33,175.90,7.15,1
76509,ffd543c2b60842e148a86870dc60e212,1a4eed32aecb25c4c294408905613487,delivered,2018-01-04 12:00:49,2018-01-05 02:35:33,2018-01-15 21:23:17,2018-01-17 20:18:44,2018-02-06,boleto,373.11,b7d94dc0640c7025dc8e3b46b52d8239,9c0e69c7bf2619675bbadf47b43f655a,2018-01-11 02:35:33,175.91,14.15,1

In [396]:
d=pd.concat([merged_orders_payments_orderItems, products],join='inner', axis=1)

In [400]:
d[d['order_id'] == '1dedb63df54bd6377bc3e2b61ec4c791']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity,product_id,product_category_name,product_photos_qty
8942,1dedb63df54bd6377bc3e2b61ec4c791,25a2fb1acc86dfbc6cd42510d83e651d,delivered,2017-11-25 06:43:15,2017-11-27 06:36:13,2017-11-28 23:18:52,2017-12-09 11:25:58,2017-12-15,credit_card,271.14,05a6b99c0460f22f5f8101493c0e3c0e,391fc6631aebcf3004804e51b40bcf1e,2017-12-01 06:36:13,69.80,30.13,1,4754d89182db4010eabbf20da5fb7191,utilidades_domesticas,1.0
8943,1dedb63df54bd6377bc3e2b61ec4c791,25a2fb1acc86dfbc6cd42510d83e651d,delivered,2017-11-25 06:43:15,2017-11-27 06:36:13,2017-11-28 23:18:52,2017-12-09 11:25:58,2017-12-15,credit_card,271.14,2481a472d98c582b46bc2dfeae6f539f,391fc6631aebcf3004804e51b40bcf1e,2017-12-01 06:36:13,59.55,16.74,1,d03e74df1b077535fb82990351bd3cac,construcao_ferramentas_jardim,6.0
8944,1dedb63df54bd6377bc3e2b61ec4c791,25a2fb1acc86dfbc6cd42510d83e651d,delivered,2017-11-25 06:43:15,2017-11-27 06:36:13,2017-11-28 23:18:52,2017-12-09 11:25:58,2017-12-15,credit_card,271.14,dde35467201d3ff9e3f8e4297aa2768e,4a3ca9315b744ce9f8e9374361493884,2017-12-01 06:36:13,89.90,5.02,1,9a9469abcf027566dce48059c28ea832,cama_mesa_banho,2.0

In [379]:
import numpy as np
import pandas as pd
from unidecode import unidecode
import re
import datetime

orders = pd.read_csv(r"Z:\Downloads\archive (13)\olist_orders_dataset.csv")

orders['order_purchase_timestamp'] = orders['order_purchase_timestamp'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))
orders['order_approved_at'] = orders['order_approved_at'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)
orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)
orders['order_estimated_delivery_date'] = orders['order_estimated_delivery_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S") if not pd.isna(x) else x)

orders = orders[(
    ((orders['order_approved_at'] - orders['order_purchase_timestamp']).dt.total_seconds() / 86400 >= 0) &
    ((orders['order_delivered_carrier_date'] - orders['order_approved_at']).dt.total_seconds() / 86400 >= 0))]

orders.reset_index(drop=True, inplace=True)

to_remove = orders[(orders['order_status']=='canceled') & (orders['order_delivered_customer_date'].notna())].index

orders.drop(to_remove, inplace=True)

orders.reset_index(drop=True, inplace=True)

orders['order_status'] = orders['order_status'].str.replace('canceled', 'cancelled')

payments = pd.read_csv(r"Z:\Downloads\archive (13)\olist_order_payments_dataset.csv")

payments.drop(columns = ['payment_sequential', 'payment_installments'], inplace=True)

payments = payments.groupby(by=['order_id', 'payment_type']).sum('payment_value').reset_index()


merged_orders_payments = pd.merge(orders, payments, how='inner', on='order_id')

order_items = pd.read_csv(r"Z:\Downloads\archive (13)\olist_order_items_dataset.csv")

merged_orders_payments_orderItems = pd.merge(merged_orders_payments, order_items, how='inner', on='order_id')

merged_orders_payments_orderItems['shipping_limit_date'] = \
        merged_orders_payments_orderItems['shipping_limit_date'].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))

merged_orders_payments_orderItems = merged_orders_payments_orderItems[(merged_orders_payments_orderItems['shipping_limit_date'] > merged_orders_payments_orderItems['order_purchase_timestamp']) & \
(merged_orders_payments_orderItems['shipping_limit_date'] > merged_orders_payments_orderItems['order_approved_at']) & \
(merged_orders_payments_orderItems['shipping_limit_date'] < merged_orders_payments_orderItems['order_delivered_customer_date'])]

merged_orders_payments_orderItems.drop(columns=['order_item_id'], inplace=True)

merged_orders_payments_orderItems = merged_orders_payments_orderItems.groupby(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date']).agg(price=("price", "sum"),
                                    freight_value=("freight_value", "sum"),
                                      quantity=("product_id", "count")).reset_index()

to_remove = merged_orders_payments_orderItems.loc[np.where(round((merged_orders_payments_orderItems['price'] + merged_orders_payments_orderItems['freight_value']), 2) > merged_orders_payments_orderItems['payment_value'])].index

merged_orders_payments_orderItems.drop(to_remove, inplace=True)

merged_orders_payments_orderItems.reset_index(drop=True, inplace=True)

reviews = pd.read_csv(r"Z:\Downloads\archive (13)\olist_order_reviews_dataset.csv")

to_remove = reviews[~reviews['order_id'].isin(merged_orders_payments_orderItems['order_id'])].index

reviews.drop(to_remove, inplace = True)

reviews.reset_index(drop=True, inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\Downloads\\archive (13)\\olist_orders_dataset.csv'

In [ ]:
merged_orders_payments_orderItems